### ISSUE TITLE
Modification: [Pause onboarding of multiple Round 4 notary's]

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/notary-governance#816] opened 2023-01-23 15:21 UTC
## Issue Description
Multiple notary's have abused the Filecoin plus program by awarding DataCap without conducting thorough due diligence in past rounds and raising flags for collusion. Secondly they have abused the layer of trust by being involved in CID Sharing. We should pause the onboarding this "new" notary's.

## Impact
https://github.com/filecoin-project/notary-governance/issues/765
https://github.com/filecoin-project/notary-governance/issues/721
https://github.com/filecoin-project/notary-governance/issues/693
https://github.com/filecoin-project/notary-governance/issues/716

Why -> PowPower / Ipollo / NDlabs / Bitrise all are the same Org. NDlabs has been proven to be involved heavily in CID sharing. 
We should not allow this organisation and their subsidy's to continiue their fraudulent behaviour.
https://github.com/filecoin-project/notary-governance/issues/571#issuecomment-1184918323

-----------

Why -> Blockchainworld / CID Sharing fraud. #408 #648
https://github.com/filecoin-project/notary-governance/issues/648

-----------

Why -> f014386 > This miner is the same of Tom -> origin storage. 2 seperate notary's on one organisation is not a good plan.
https://github.com/filecoin-project/notary-governance/issues/770 (1475Notary).

-----------

Why -> https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1109#issuecomment-1290290728
Paying notary's to get your datacap approved is not the way to go. Notary's should have a clean sheet.
https://filecoinproject.slack.com/archives/C036JKD8NVA/p1665381437456629
https://filecoinproject.slack.com/archives/CPFTWMY7N/p1664046423621259
https://github.com/filecoin-project/notary-governance/issues/639

## Proposed Solution(s)
Pause the onboarding of the above notary's so the community has more time to see what is going on and limit the risk of further abuse.

### Timeline
1. Proposal discussion 2023 Governance calls.
2. Pause onboarding of this new round 4 notary's.
3. Action taken based on community consensus

**Comment by herrehesse** [comment] 2023-01-25 10:46
I wholeheartedly endorse this proposal. Given the ongoing discussions and investigations regarding notaries, it would be imprudent to introduce a large number of new notaries at this time.

It would be wise to wait until proper regulations and oversight measures are in place, including the establishment of an independent entity to address disputes and provide opportunities for learning and improvement.

**Comment by psh0691** [comment] 2023-01-26 04:05
Hi, @cryptowhizard.

In Korea, where I live, the "Lunar New Year" holiday is now over. I was surprised to see your suggestions and many discussions back at work.

First of all, I would like to express my respect and appreciation for your interest and passion for FIL+.
I thought it would be nice if there was a discussion and agreement on the right growth of the file coin network earlier. But I do agree with you now that you and @herrehesse want to move in the right direction with a lot of effort.

I also fully acknowledge the allegations made against me.
1. We acknowledge that there have been cases of signing as notaries without due diligence. 
So far, it has been signed at the request of DM according to arbitrary judgment and standards, but it admits that technical judgment has been insufficient.

2. It is recognized that it is involved in CID sharing. 
I didn't know about #166 I applied for until the CID inspection bot came out, but it was my negligence. I also acknowledge the CID sharing of LDN that I signed.

Therefore, I will follow the governance's decision on the technical lack and rashness of due diligence, and wish for the right FIL+ growth.

In addition, even though he/she was selected as a notary public, due diligence and signature were not made, or poor notary publics need to be reviewed.

There are other things I hope to improve about FIL+, I will share them as soon as my thoughts are organized.

**Comment by herrehesse** [comment] 2023-01-26 06:43
@psh0691 This is the friendliest and most honest answer we got so far. Really appreciated.

**Comment by kernelogic** [comment] 2023-01-27 23:41
@psh0691 I believe your signings were out of good will, to accelerate Time-To-Datacap. I too didn't know about CID sharing mechanism until the bot is online. There are many ways to abuse the system, CID sharing is only one of them. Hopefully more tools will be available to catch more mechanisms.

**Comment by Carohere** [comment] 2023-02-05 15:19
Adding notaries that I think need to be put on hold

1. #697 
![Snipaste_2023-02-05_14-44-30](https://user-images.githubusercontent.com/106579285/216826967-249ee07d-ef40-4bb8-aa4c-fe0f04e918b4.png)
![Snipaste_2023-02-05_14-45-08](https://user-images.githubusercontent.com/106579285/216826975-8db1418c-370a-40d8-8715-64aca481ec0b.png)

- The data and clients are fake & have no value to the network 
- NDLabs lied in the previous disclosure #571, these notaries are obviously colluding

2. #638 
- KYC was not done by business email
- No proof of operation in EU
- Flagged this applicant several times since december and never received any response

**Comment by NDLABS-OFFICE** [comment] 2023-02-06 03:35
Hello @Carohere 
Thank you for pointing it out. We apologize for the issue with data sharing, it was caused by technical problems with early data distribution. I can also explain the detailed reason for this issue to you later. 
Additionally, there are a few points I would like to clarify:
1. The ND's LDN application form encased DC has been revoked on the chain and will not be used again. We have mentioned this before. 
2. Other four notaries also stopped encasing to avoid identity-sharing issues, you can check the time of LDN.
3. The clients and data of these entities are real, we have connected with the case study team offline multiple times and provided proof of stored data CID. This is promotional information.
IPOLLO: https://filecoin.io/blog/posts/case-study-ipollo-guarantees-ownership-in-the-metaverse-with-content-persistence-and-interoperability/
NFTSTAR: https://filecoin.io/blog/posts/case-study-why-nftstar-trusts-decentralized-cloud-storage-for-sports-collectibles/
4. The relationship between these entities was discussed a long time ago in V3, and we honestly disclosed it. And except for ND, none of the other entities joined in V3, and there won't be any problem with the notary collusion. People are just worried about multiple organizations having open large data set applications, which could result in an entity or a group of entities completely playing the role of client, notary, and storage provider, violating the notary agreement and the value and intention of the Filecoin Plus plan and DataCap.
So the information has been disclosed, and they will not have the problem of identity overlap. It's reasonable for entities with overlapping businesses.
5. Additionally, regarding our data distribution technology issues, we have made modifications, you can check #1521 ~ #1524, and all SPs can be publicly retrieved.

To reiterate, the encapsulation issue of LDN is a technical problem and has nothing to do with the notary role. There was no concealment during the notary application process, and these notaries have never been onboarded, they should not be labeled as "liars."

**Comment by Louise615** [comment] 2023-02-06 09:53
Filecoin has always been an inclusive DAO community, I don't see the need to weed out notaries. For their contributions over time, they deserve a chance to prove that they're capable and will comply with the rules.

**Comment by cryptowhizzard** [comment] 2023-02-06 10:15
> Filecoin has always been an inclusive DAO community, I don't see the need to weed out notaries. For their contributions over time, they deserve a chance to prove that they're capable and will comply with the rules. However, actions have consequences. Doing something wrong and not being punished will only encourage evil doers. For example, Origin storage is the largest sp in the Chinese community and is part of ChainUp, the largest Web3 investment group in China. Unfortunately, as the leading orgnization in the Chinese filecoin community, they are not guiding in the right way...
> 
> In order to set proper community guidelines and warn all notaries on board. I suggest suspending the notaries mentioned in #811 and here from signing for 6 months. But in the meantime they can review the application and do due diligence. Future decisions on whether to resume will be based on the community's inputs of their engagements.

This has nothing to do with inclusivity. It has to do with that one has to have a clean reputation. Just as in real life one has to have a state of conduct for a certain job. Being a notary is one of them.

**Comment by Carohere** [comment] 2023-02-06 10:59
> 4\. The relationship between these entities was discussed a long time ago in V3, and we honestly disclosed it. And except for ND, none of the other entities joined in V3, and there won't be any problem with the notary collusion. People are just worried about multiple organizations having open large data set applications, which could result in an entity or a group of entities completely playing the role of client, notary, and storage provider, violating the notary agreement and the value and intention of the Filecoin Plus plan and DataCap.

First, disagree with your point about CID sharing. CID sharing can only happen to related LDN apps and apparently, that's not the case with you. Second, the real problem is all of your related organizations #693 #716 #721 #765 are now in v4 and let's be honest, there's no way to track if the client/sp is who they claim to be...

**Comment by NDLABS-OFFICE** [comment] 2023-02-06 11:30
I would like to reiterate that we will not explain this issue again in the future. How other related notaries will act in the future is nothing to do with ND.

**Comment by Chris00618** [comment] 2023-02-06 11:50
> Filecoin has always been an inclusive DAO community, I don't see the need to weed out notaries. For their contributions over time, they deserve a chance to prove that they're capable and will comply with the rules. However, actions have consequences. Doing something wrong and not being punished will only encourage evil doers. For example, Origin storage is the largest sp in the Chinese community and is part of ChainUp, the largest Web3 investment group in China. Unfortunately, as the leading orgnization in the Chinese filecoin community, they are not guiding in the right way...
> 
> In order to set proper community guidelines and warn all notaries on board. I suggest suspending the notaries mentioned in #811 and here from signing for 6 months. But in the meantime they can review the application and do due diligence. Future decisions on whether to resume will be based on the community's inputs of their engagements.

The **6 months** freezing period is appropriate. Of course, we should also allow these notaries to resume their status as notaries after 6 months of training. This month we will have nearly 100 notaries. We need to establish a rule ASAP to restrain these notaries who repeatedly violate the rules, otherwise it will be chaotic.

**Comment by cryptowhizzard** [comment] 2023-02-06 11:52
> > Filecoin has always been an inclusive DAO community, I don't see the need to weed out notaries. For their contributions over time, they deserve a chance to prove that they're capable and will comply with the rules. However, actions have consequences. Doing something wrong and not being punished will only encourage evil doers. For example, Origin storage is the largest sp in the Chinese community and is part of ChainUp, the largest Web3 investment group in China. Unfortunately, as the leading orgnization in the Chinese filecoin community, they are not guiding in the right way...
> > In order to set proper community guidelines and warn all notaries on board. I suggest suspending the notaries mentioned in #811 and here from signing for 6 months. But in the meantime they can review the application and do due diligence. Future decisions on whether to resume will be based on the community's inputs of their engagements.
> 
> The **6 months** freezing period is appropriate. Of course, we should also allow these notaries to resume their status as notaries after 6 months of training. This month we will have nearly 100 notaries. We need to establish a rule ASAP to restrain these notaries who repeatedly violate the rules, otherwise it will be chaotic.

That chaos has already started. #816 notary’s already started signing on applications with fraud. It has to stop , right now 😡

**Comment by Chris00618** [comment] 2023-02-06 12:19
@cryptowhizzard  You also need to restrict your behavior with Yanfei. Otherwise, you will get into trouble immediately.

![image](https://user-images.githubusercontent.com/105741726/216968356-79b6bd17-3aea-4038-8ce9-38003cfd565e.png)

**Comment by cryptowhizzard** [comment] 2023-02-06 12:27
> @cryptowhizzard You also need to restrict your behavior with Yanfei. Otherwise, you will get into trouble immediately.
> 
> ![image](https://user-images.githubusercontent.com/105741726/216968356-79b6bd17-3aea-4038-8ce9-38003cfd565e.png)

Explain?

**Comment by Neal-fil** [comment] 2023-02-07 09:24
The scale of R4 notaries is huge enough to cover the daily community work. Favor suspension of all notaries involved and clearer guidelines for Fil+ especially during the onboarding stage.

**Comment by NDLABS-OFFICE** [comment] 2023-02-07 09:28
@Neal-fil How many active notaries are there?

**Comment by Neal-fil** [comment] 2023-02-07 09:38
@NDLABS-OFFICE https://github.com/filecoin-project/notary-governance/blob/main/notaries/README.md

**Comment by Carohere** [comment] 2023-02-07 09:42
> > Filecoin has always been an inclusive DAO community, I don't see the need to weed out notaries. For their contributions over time, they deserve a chance to prove that they're capable and will comply with the rules. However, actions have consequences. Doing something wrong and not being punished will only encourage evil doers. For example, Origin storage is the largest sp in the Chinese community and is part of ChainUp, the largest Web3 investment group in China. Unfortunately, as the leading orgnization in the Chinese filecoin community, they are not guiding in the right way...
> > In order to set proper community guidelines and warn all notaries on board. I suggest suspending the notaries mentioned in #811 and here from signing for 6 months. But in the meantime they can review the application and do due diligence. Future decisions on whether to resume will be based on the community's inputs of their engagements.
> 
> This has nothing to do with inclusivity. It has to do with that one has to have a clean reputation. Just as in real life one has to have a state of conduct for a certain job. Being a notary is one of them.

@cryptowhizzard hi, by "pause" do you mean for a certain period of time or more a complete removal? I don't quite get how exactly you want to address this issue.

**Comment by cryptowhizzard** [comment] 2023-02-07 09:46
> > > Filecoin has always been an inclusive DAO community, I don't see the need to weed out notaries. For their contributions over time, they deserve a chance to prove that they're capable and will comply with the rules. However, actions have consequences. Doing something wrong and not being punished will only encourage evil doers. For example, Origin storage is the largest sp in the Chinese community and is part of ChainUp, the largest Web3 investment group in China. Unfortunately, as the leading orgnization in the Chinese filecoin community, they are not guiding in the right way...
> > > In order to set proper community guidelines and warn all notaries on board. I suggest suspending the notaries mentioned in #811 and here from signing for 6 months. But in the meantime they can review the application and do due diligence. Future decisions on whether to resume will be based on the community's inputs of their engagements.
> > 
> > 
> > This has nothing to do with inclusivity. It has to do with that one has to have a clean reputation. Just as in real life one has to have a state of conduct for a certain job. Being a notary is one of them.
> 
> @cryptowhizzard hi, by "pause" do you mean for a certain period of time or more a complete removal? I don't quite get how exactly you want to address this issue.

I mean pause until a definitive decision is made how we are going to handle this.

**Comment by Kobayashi-interflex** [comment] 2023-02-07 11:47
We take actions seriously in Japan, even kids know to be responsible for what they did. 6 month suspension is meaningless. We should clean up the ecosystem during the bear market. Pretend the violation is nothing will eventually drag FIL down. I seriously hope people who are profiting from this project can be more respectful of the meaning of data.

**Comment by powpower2022** [comment] 2023-02-07 13:18
We have been committed to the offline promotion of filecoin and the holding of conferences since the launch of filecion. We applied for a notary in v3. During this period, we have been communicating with the governance team and participating in video conferences to explain because of the business relationship. We actively participated in the notary meeting and did not violate the rules of fil+ during this period. Regarding the issue of "pre-disclosure", we have made the information open and transparent. What else do we need to do?

**Comment by cryptowhizzard** [comment] 2023-02-07 13:25
> We have been committed to the offline promotion of filecoin and the holding of conferences since the launch of filecion. We applied for a notary in v3. During this period, we have been communicating with the governance team and participating in video conferences to explain because of the business relationship. We actively participated in the notary meeting and did not violate the rules of fil+ during this period. Regarding the issue of "pre-disclosure", we have made the information open and transparent. What else do we need to do?

My problem is with this:

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?q=is%3Aissue+ipollo

What happened here. Why did the FIL+ program get abused on behalf of Ipollo in each and all of those applications?
Who earned those block rewards with that extra Qa power over the back of the hard working people in this community?

**Comment by powpower2022** [comment] 2023-02-07 13:34
@cryptowhizzard Suggest adding your notary to the proposal

**Comment by cryptowhizzard** [comment] 2023-02-07 13:36
> @cryptowhizzard Our LDN application form was disabled during our V3 notary review period. If there is a problem of data abuse, please take a look at your own practices. [filecoin-project/filecoin-plus-large-datasets#1529](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1529) [filecoin-project/filecoin-plus-large-datasets#1549](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1549)

Uhm, you asked a question. I gave you an answer. You asked me what you should do to "get this over with" ... at least that is how i read your response. I answered you -> Explain because i have never read an explanation for it.

**Comment by powpower2022** [comment] 2023-02-07 13:39
@cryptowhizzard We will wait for the governance team to deal with it, and we accept any outcome. As for you, please strictly abide by the fil+ specification. Demand yourself the way you demand others.

**Comment by cryptowhizzard** [comment] 2023-02-07 13:43
> @cryptowhizzard We will wait for the governance team to deal with it, and we accept any outcome. As for you, please strictly abide by the fil+ specification. Demand yourself the way you demand others.

Ok, you ask a question , you get an answer and then you start bashing out against someone else and still you refuse / fail to give a normal explanation on what happened. Why is that so difficult? 

In round 3 there was no CID checker so we could not see what you were doing. Now we can and now we ask.

**Comment by powpower2022** [comment] 2023-02-07 13:46
We applied for LDN, because the community does not allow LDN's client identity to coincide with the notary identity, so we stopped business cooperation. The LDN application form is also discontinued. The problem of cid sharing has nothing to do with us, we are responsible for providing real data of our business. Here is my answer. Now please answer my question, what happened to this LDN?
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1529
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1549

**Comment by cryptowhizzard** [comment] 2023-02-07 13:59
Hi @powpower2022 

It still does not seem to land with you does it? 

You asked what the problem is why i started this issue. I explained.
You asked what questions there were to answer, I explained.

The explanation you give is "The problem of cid sharing has nothing to do with us, we are responsible for providing real data of our business. " 

Fine --> Have you just opened the link there I gave you and taken a look with all the abusive LDN's where your name is in? Are you going to tell me that all those contact moments Protocol Labs was talking to the wrong Ipollo imposters? If so, why don't they respond here and tell this so we can relax and move forward?

If you say " We have nothing to do with it " then i don't mind taking that for an answer , but the question remains who does? And it is a normal question. No need to reflect that away in an aggressive way. You are (still) a notary. Behave like it. And if something did happen that could not see the daylights .... that's life. Deal with it.

**Comment by powpower2022** [comment] 2023-02-07 14:01
@cryptowhizzard The following disputes will be moot, we will wait for the results of the governance team.

**Comment by fillove** [comment] 2023-02-07 14:02
@cryptowhizzard  Filecoin belongs to the community. Regarding the issue, you can submit it and add anyone you want to submit it. I can submit it too. Anyone can create a new issue, and anyone has the right to include you.

So, even if you are not here, please answer the questions and face up to the problems you see.

Filecoin is fair and equal.

The questions you ask should be taken seriously.

When someone asks you a question, please answer it seriously, instead of asking endlessly.

**Comment by fillove** [comment] 2023-02-07 14:03
For example, can you explain this question?
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1529
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1549

**Comment by cryptowhizzard** [comment] 2023-02-07 14:04
> For example, can you explain this question? [filecoin-project/filecoin-plus-large-datasets#1529](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1529) [filecoin-project/filecoin-plus-large-datasets#1549](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1549)

Yes , sure. Just open the links and check yourself???

**Comment by cryptowhizzard** [comment] 2023-02-07 14:07
> @cryptowhizzard Filecoin belongs to the community. Regarding the issue, you can submit it and add anyone you want to submit it. I can submit it too. Anyone can create a new issue, and anyone has the right to include you.
> 
> So, even if you are not here, please answer the questions and face up to the problems you see.
> 
> Filecoin is fair and equal.
> 
> The questions you ask should be taken seriously.
> 
> When someone asks you a question, please answer it seriously, instead of asking endlessly.

I never said that Filecoin did not belong to the community.

However , beeing a notary you need to stand out to the community. You can't stand out to the community with a track record [like this 
](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?q=is%3Aissue+ipollo) unless you want to make a fool over everyone around here. Secondly there is still no explanation given for what happened.

**Comment by fillove** [comment] 2023-02-07 14:13
dear

You are a great community member

You are an exceptional individual not affiliated with any interest group

please comment

![217223419-130b1d8a-1c3d-4fd5-80c5-c811becfc1d5](https://user-images.githubusercontent.com/123223386/217268108-fbbc1c39-cbb6-4eea-8dfc-111e330f84c9.png)

**Comment by fillove** [comment] 2023-02-07 14:14
dear @Carohere 

You are a great community member

You are an exceptional individual not affiliated with any interest group

please comment

**Comment by fillove** [comment] 2023-02-07 14:14
![217223419-130b1d8a-1c3d-4fd5-80c5-c811becfc1d5](https://user-images.githubusercontent.com/123223386/217268985-b6872d2b-a9a6-461c-9eea-1577253d1fed.png)

**Comment by Carohere** [comment] 2023-02-08 17:09
> ![217223419-130b1d8a-1c3d-4fd5-80c5-c811becfc1d5](https://user-images.githubusercontent.com/123223386/217268985-b6872d2b-a9a6-461c-9eea-1577253d1fed.png)

@fillove, appreciate it but i don't get what you mean by this. Could you elaborate a bit more? Also, different topics of discussion will lower the efficiency. If you have any concerns about @cryptowhizzard, please start a new issue to discuss and share the proof 🙏

**Comment by Neal-fil** [comment] 2023-02-09 05:44
> We take actions seriously in Japan, even kids know to be responsible for what they did. 6 month suspension is meaningless. We should clean up the ecosystem during the bear market. Pretend the violation is nothing will eventually drag FIL down. I seriously hope people who are profiting from this project can be more respectful of the meaning of data.

FIL is worthless without notary onboard clients. It's unfair for long term participants to get disqualified for a few mistakes. We need to accredit the contributions that these notaries bring to the network. 6 month is enough punishment.

**Comment by fillove** [comment] 2023-02-12 14:07
#824

**Comment by fillove** [comment] 2023-02-12 14:16
@flyworker

you just need to answer one thing：

Who should be responsible for the evil deeds in 924?

**Closed as completed** 2023-06-01 16:10 UTC
Labels: Proposal
