### ISSUE TITLE
Recommendation for pausing signing by listed notaries for abusing Filecoin Plus

### ISSUE THREAD

**Issue by raghavrmadya** [filecoin-project/notary-governance#892] opened 2023-06-26 00:53 UTC
## Issue Description
Based on the signing behavior on the [ following application ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1938), the notaries have ignored flags raised by other notaries and are being investigated for abusing DC. 

The list is as follows: 

AthSmith
BobbyChoii
Casey-PG
Meibuy
Suyanj
TakiChain

## Impact
Investigation can result in the removal of the aforementioned notaries
### Proposed Timeline
Discussion on June 27th T&T WG call. 
The decision announced on June 30th 2023 at 5:01 PM EST

### Technical dependencies 
Removal from the main multi-sig

**Comment by Casey-PG** [comment] 2023-06-26 05:53
We would like to provide some background regarding the application mentioned:

**Timeline**
On May 2, a notary questioned the retrieval problem. On May 4, the client responded that the retrieval process works and provided screenshots. On May 6th, we trigged the checker and confirmed that the Datacap and CID report was in order. After confirming that the notary who had previously raised the issue was aware of the status of the request, we signed the second round of allocation.

**Our signature**
We have confirmed the description, DC usage report, retrieval result, and we definitely considered feedback from other notaries in application #1938. We find it difficult to understand the accusation about "ignored flags raised by other notaries" posed to us.

As we shared many times before, as a media company we do our best to verify the legitimacy of applications. We value the importance of data and LDN's guidelines. We are dedicated to loading more valuable data into the network. We understand and appreciate that retrieval is an important component of the network. In particular, prior to the launch of retrieval checker, we had several calls for retrieval tutorials in hopes of facilitating notary access with a more visual approach to the data and freeing up the reliance on technical background. 

We are pleased to see the launch of the retrieval checker. It allows everyone to verify the retrieval success rate, a good factor for determining the compliance of applications. With the new function available, we sincerely hope that the governance team can give a clear definition of what kind of sign-off is acceptable and what is not for a clearer environment in Filplus project.


Best Regards,
PangodGroup Team

**Comment by kevzak** [comment] 2023-06-27 17:22
Hi @Casey-PG - In my review, I was not concerned at all with retrievability for this application. Although it is also an issue. 

But, I am concerned more about the details of the applicant and SPs.

As you can see here https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1938#issuecomment-1518947769, @zcfil asked some questions to start to the applicant. There was no answer. 

Who is the applicant? A new member to Filecoin? Or with experience? They must be experienced to be onboarding 1PiB+ per week recently. 

And are they the data preparer? How are they preparing the data?

And how did the applicant find SPs? Who are the SP businesses involved? Do they have 2-3-4-5 SP groups?

The applicant mentioned for the question "In which geographies do you plan on making storage deals" - Asia other than Greater China, North America, Europe. But if you look at CID report it seems like 1-2 notaries in China/HK.

These are all flags when I look at this. And yet, not one of the signing notaries asked any of these types of questions. They just leave comments that are copied and pasted verbatim from other applications.

**Comment by AthSmith** [comment] 2023-06-28 10:45
Thanks KevinZ, we got your point, this is a very interesting discussion, please allow us to express our opinions.

The purpose of electing so many notaries in the community is to speed up and optimize the application process, which also means that applicants do not have to obtain the support of all notaries to have their data storing properly. And, we'd like to get more input on three points:

1. Clients should have the right to selectively ignore questions from some notaries if there is no clear abuse of FIL+ rules. Of course, clients can cooperate if they wish to have their support and trust;
2. Any notary should have the right to choose how DD is conducted, unless there is clear evidence from other members that these applications against specific rules. Maybe you trust and respect some applicants or SPs ,but other notaries do not know them at all.
3. If anyone has questions about these applications, they can feel free to ask them directly. The applicants may respond to you, but may not respond to you if they do not need your support any more. But any way, notaries should not be challenged, as according to the rules they do not have any official return.

The reason why FIL+ project is criticized is that the current rules generally ignore the rights and claims of clients, resulting in real clients not being respected in the true sense of the word here, and the series of disorders caused is justifiable. We need to make some changes that will allow FIL+ to go farther and allow SPs to gradually stop acting as applicants. This is far more valuable than discussing the removal of some notaries. Thank you!

**Comment by herrehesse** [comment] 2023-06-28 12:23
I fully support the proposal to remove the mentioned notaries due to the significant abuse, lack of due diligence, and ongoing signing of highly questionable applications. 

Statements like "_notaries should not be challenged_" and "_Clients should have the right to selectively ignore questions from some notaries_" would be an imminent removal in my opinion.

It is crucial to prioritise accountability and responsible behaviour within the notary system.

**Comment by Meibuy** [comment] 2023-06-29 16:20
Hi RG, we understand how you feel recently, but we prefer this to be a misunderstanding, it would be much appreciated if you can ask the notaries on the list for their opinions before making such a drastic proposal? It would make the community atmosphere even less friendly that we don't expect.

Frankly, none of us are perfect, @raghavrmadya , we are willing to do our best to be better, but please give some time to us community partners. Thanks a lot!

**Comment by raghavrmadya** [comment] 2023-06-30 17:31
Hi, in my role, I'm not much concerned about notary opinions. I'm interested in data, facts, and patterns. Having an opinion is a privilege, not a right. This list is not an opinion, it's based on facts.

**Comment by raghavrmadya** [comment] 2023-06-30 17:33
Given that aforementioned notaries have not provided sufficient evidence to prove that they acted in good faith, I would request the RKH to remove the aforementioned notaries from the main multisig after 5 PM EST today

**Comment by Casey-PG** [comment] 2023-07-01 02:50
> We would like to provide some background regarding the application mentioned:
> 
> **Timeline** On May 2, a notary questioned the retrieval problem. On May 4, the client responded that the retrieval process works and provided screenshots. On May 6th, we trigged the checker and confirmed that the Datacap and CID report was in order. After confirming that the notary who had previously raised the issue was aware of the status of the request, we signed the second round of allocation.
> 
> **Our signature** We have confirmed the description, DC usage report, retrieval result, and we definitely considered feedback from other notaries in application #1938. We find it difficult to understand the accusation about "ignored flags raised by other notaries" posed to us.
> 
> As we shared many times before, as a media company we do our best to verify the legitimacy of applications. We value the importance of data and LDN's guidelines. We are dedicated to loading more valuable data into the network. We understand and appreciate that retrieval is an important component of the network. In particular, prior to the launch of retrieval checker, we had several calls for retrieval tutorials in hopes of facilitating notary access with a more visual approach to the data and freeing up the reliance on technical background.
> 
> We are pleased to see the launch of the retrieval checker. It allows everyone to verify the retrieval success rate, a good factor for determining the compliance of applications. With the new function available, we sincerely hope that the governance team can give a clear definition of what kind of sign-off is acceptable and what is not for a clearer environment in Filplus project.
> 
> Best Regards, PangodGroup Team

@raghavrmadya We have provided the details of issue #1938, can you tell me which part you disagree that we are acting in good faith?

https://github.com/filecoin-project/notary-governance/issues/882#issuecomment-1552796176
https://github.com/filecoin-project/notary-governance/issues/882#issuecomment-1575977454
https://github.com/filecoin-project/notary-governance/issues/882#issuecomment-1615382229
We have also responded several times under the previous issue, please check and let us know what we missed.

Thank you!
Casey, PangodGroup

**Comment by claydrone** [comment] 2023-07-01 02:52
> Hi, in my role, I'm not much concerned about notary opinions. I'm interested in data, facts, and patterns. Having an opinion is a privilege, not a right. This list is not an opinion, it's based on facts.

I think the notary has the right to show opinion.

**Comment by fsector-1** [comment] 2023-07-01 03:44
> 你好，就我的角色而言，我不太关心公证人的意见。我对数据、事实和模式感兴趣。发表意见是一种特权，而不是权利。这份清单不是意见，而是基于事实。

Hi @raghavrmadya 
As a member of the filecoin community, I'm disappointed to hear you say this. 
1. Isn't the occurrence of data and events triggered by notary public? 
2. The notary is also a member of the community/You are also a member of the community, and you are paid to work, the notary is a voluntary worker, you should listen to the advice but not necessarily take it.

**Comment by fsector-1** [comment] 2023-07-01 03:46
> Hi, in my role, I'm not much concerned about notary opinions. I'm interested in data, facts, and patterns. Having an opinion is a privilege, not a right. This list is not an opinion, it's based on facts.

Hi @raghavrmadya 
As a member of the filecoin community, I'm disappointed to hear you say this. 
1. Isn't the occurrence of data and events triggered by notary public? 
2. The notary is also a member of the community/You are also a member of the community, and you are paid to work, the notary is a voluntary worker, you should listen to the advice but not necessarily take it.

**Comment by fsector-1** [comment] 2023-07-01 03:51
> > Hi, in my role, I'm not much concerned about notary opinions. I'm interested in data, facts, and patterns. Having an opinion is a privilege, not a right. This list is not an opinion, it's based on facts.
> 
> I think the notary has the right to show opinion. Even though the words may not be something you like or even wrong, they still have the right to speak.

I agree with @claydrone  very much, can not have a dictatorial idea, even do not listen to the views of the community, everything to the overall situation

**Comment by TakiChain** [comment] 2023-07-01 05:48
Hi @raghavrmadya,
If you need to give additional explanations based on which facts, please list them in detail.

Based on the premise of wanting to improve the FIL+ experience and process, we promise that everything we do is based on good intentions. This includes our signing in #1938.

And, we are willing to continuously improve our signing actions to help more cleints could easily onboard under the FIL+ rules.
Thanks.

**Comment by Suyanj** [comment] 2023-07-01 06:11
We'd like to state the facts and what happened:

After talking with the applicant, we think the dataset is real and the applicant can be trusted, so we did sign it once on May 25, but we didn't find any problems and the report showed normal, and also the client gave a screenshot of the successful retrieval.

@raghavrmadya  I think you should clarify WHEN the notice to suspend signing from you was issued? 

PS: Thank you so much if you could respond to the notary's fact-based questions.

**Comment by cryptowhizzard** [comment] 2023-07-01 07:01
I think that this decision is the right one.

<img width="511" alt="Scherm­afbeelding 2023-07-01 om 08 57 02" src="https://github.com/filecoin-project/notary-governance/assets/36404435/67fa6cac-aca1-4212-85d4-4f9118b27190">

The community has been deliberately fooled by this notary's signing for this application. There has been no real KYC and the notary's still signed despite that none of this data could be checked if the data stored is real. You all knew since i gave you this information and you could have checked yourself.

We have been over and over this discussion many times, but now that it is clear that this data is not retrievable and never will be retrievable against the FIL+ program guidelines, please take your responsibility and stop harassing the community.

**Comment by cryptowhizzard** [comment] 2023-07-01 07:07
> we wanna contest the recommendation / decision.
> 
> we have questions and we expect this to be stopped until all questions are answered by those who participated in the process and the decision making.

Can you be more specific in the parts that you contest? Do you think that the data presented ( 0% retrievability ) is inadequate? Do you see that these notaries held off from signing when i posted this here at [may 2th?](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1938#issuecomment-1531188064)

**Comment by cryptowhizzard** [comment] 2023-07-01 07:23
> there are a few decision that have been made that in my eyes lack community discussion. i cannot find the evidence brought against the prosecuted. i cannot find a comprehensive written reasoning about the ruling that was made here or who made it and i am pretty much pretty unsure what the exact process of this is actually looks like.
> 
> i do not expect this to be decided but brought in front of a sufficient amount of community members to come to an agreement that a trial is needed, wanted. same for the "ruling"

Ok, so when i read this clear , you don't object against the facts presented here. You object against the procedures taken and consequenses.

I am aware that there has been friction between you and others in the community. I would however appreciate it if you would not block actions that need to be taken for the benefit and safety of the community. If we allow non retrievable data to be stored and notaries sign on this we open the door for ChildPorn / Copyright violations and all other kinds of garbage.

**Comment by cryptowhizzard** [comment] 2023-07-01 07:39
@f8-ptrk 

I did my job. I have gathered evidence against the retrievability of this LDN here , 2 months ago. 
Since that time there has been 0% retrievability and other notaries decided to disregard my facts harming the safety and trust of the community of Filecoin by not doing proper duediligence themselves. Now it is time to hold them responsible.

Lotus client retrieve is the command that can be used to test retrievability but you are intelligent and well aware of that.

**Comment by cryptowhizzard** [comment] 2023-07-01 07:52
> and the community agreed that we should proceed with a "trial" after you brought the evidence? where is the documentation on how community consent on that was gathered? who then made the decision to move this to the trial stage here? and why? who signed off this trial in the name of the community? where is the documentation?
> 
> > Now it is time to hold them responsible.
> 
> it was time 3 years ago!

Whatever your reasons and motivations are, we can agree that I did my job here and there is enough evidence against the lack of retrievability and notaries disregarding this.

If you want to debate about procedures etc. then i suggest to look for a appropiate moment in time and with regards to the safety and trust of this community. My opinion is that these notary's should at least be put on hold for signing at the least for benefit and safety of the Filecoin community. Given their behaviour I am also in favor of removing them but that can be debated in further calls and gatherings.

Are you also in favor putting them on hold given the current evidence?

**Comment by cryptowhizzard** [comment] 2023-07-01 07:59
> i do not know what your job here is. are you getting paid? who guarantees us that you, you are well aware of this, do not act in the interest of your own business against your competitors?

Come'on. This is not the way for having debate slandering me. 

Anyway, take your time and let us know above if you are in favor putting above notaries on hold given the current evidence in LDN https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1938

**Comment by cryptowhizzard** [comment] 2023-07-01 08:06
> > Whatever your reasons and motivations are, we can agree that I did my job here and there is enough evidence against the lack of retrievability and notaries disregarding this.
> 
> i contest that an "must be retrievable/reachable" via the on chain published data is a rule and see no reason why a notary shouldn't be allowed to sign it. sure. especially for past applications - all this here seems to be a newer thing.
> 
> i have no time to look at your evidence. i have no time to attend your groups calls. i expect you, as this seems to be "your job", to present all i am asking here to me as a community member so i can make decision to support or oppose this.
> 
> > Discussion on June 27th T&T WG call.
> > The decision announced on June 30th 2023 at 5:01 PM EST
> 
> thats 3 days.... the call is offline....what do you expect me to do? accept this?

You don't have to contest retrievability.

https://github.com/filecoin-project/filecoin-plus-large-datasets/

> Stored data should be readily retrievable on the network and this can be regularly verified (though the use of manual or automated verification that includes retrieving data from various miners over the course of the DataCap allocation timeframe). At this time all LDNs may have full retrievability, but it is not required. Each project should specify what portion of the data is retrievable and provide justification. From there notaries can decide during the due diligence phases if the client’s application is justifiable and can agree to sign it or not.

"i have no time to look at your evidence. i have no time to attend your groups calls. i expect you, as this seems to be "your job", to present all i am asking here to me as a community member so i can make decision to support or oppose this"

Sorry but this is not ok. You are projecting your anger and emotions here towards me. The reading of this issue takes one minute time and sufficient thoughts to make an educated opinion if above notaries should be put on hold ( at least )

Good luck

**Comment by cryptowhizzard** [comment] 2023-07-01 08:13
> the decision has been made. i need the dicision to be revoked before i can agree to that. or i am wasting my time. don't i?

You are asking for a debate on my free Saturday morning about my work i have done for the benefit of Filecoin presenting evidence about the retrievability of this LDN. However, if you debate one should be open to both sides and open to listen. 

I listened to you and concluded that you don't have an argument against the facts i presented in this LDN issue. It is in my humble opinion not the time nor place to hold of on action and put the affected notary's on hold for the benefit of the community. This gives you opportunity to enter debate about procedures etc in the next weeks while we hold of on irriversible decisions removing them from the multisig.

My conclusion is that you are not open for this and stuck in your emotions.

**Comment by claydrone** [comment] 2023-07-01 15:45
Here is another case clear shows that @raghavrmadya  is using "presumption of guilt." when manage the T&T

in #898 

RG claim that 

`The following notaries have been accused of collusion with certain clients and an audit their signing shows evidence of possible collusion -
`
and he also said 
`No evidence, no case" is a convenient way to dodge questions. I'm basing my issue on your signing behaviour across multiple applications since February. I do not see value in listing all the application # here`

He can not give any evidence  of "accused of collusion".

He gives a timeline:
```

Discussion at June 27th 2023 WG Call
Community open audit until June 30th 2023 at 5 pm ET
Decision announced async at 5:01 pm ET
```



The issue is not discussed on June 27th 2023 WG Call
He made decision before 5:01 pm ET,June 30th 2023

We hereby can see how RG trying to use the power of the governance as he wishes. It is clearly a abuse of power.

**Comment by cryptowhizzard** [comment] 2023-07-01 16:50
> Here is another case clear shows that @raghavrmadya is using "presumption of guilt." when manage the T&T
> 
> in #898
> 
> RG claim that
> 
> `The following notaries have been accused of collusion with certain clients and an audit their signing shows evidence of possible collusion - ` and he also said `No evidence, no case" is a convenient way to dodge questions. I'm basing my issue on your signing behaviour across multiple applications since February. I do not see value in listing all the application # here`
> 
> He can not give any evidence of "accused of collusion".
> 
> He gives a timeline:
> 
> ```
> 
> Discussion at June 27th 2023 WG Call
> Community open audit until June 30th 2023 at 5 pm ET
> Decision announced async at 5:01 pm ET
> ```
> 
> The issue is not discussed on June 27th 2023 WG Call He made decision before 5:01 pm ET,June 30th 2023
> 
> We hereby can see how RG trying to use the power of the governance as he wishes. It is clearly an abuse of power.

I don’t understand what you mean here. This issue contains an LDN with extensive evidence about what happened. There is no debate about this.

Do you mean that you dispute the evidence given or do you mean that the procedure followed is not correct? What exactly is your role in the T&T working group?

**Comment by claydrone** [comment] 2023-07-01 16:54
> 
I am asking RG not you. Let him answer first.
About my role, a community member, and defendant for bq1024.

**Comment by claydrone** [comment] 2023-07-01 16:55
> > Here is another case clear shows that @raghavrmadya is using "presumption of guilt." when manage the T&T
> > in #898
> > RG claim that
> > `The following notaries have been accused of collusion with certain clients and an audit their signing shows evidence of possible collusion - ` and he also said `No evidence, no case" is a convenient way to dodge questions. I'm basing my issue on your signing behaviour across multiple applications since February. I do not see value in listing all the application # here`
> > He can not give any evidence of "accused of collusion".
> > He gives a timeline:
> > ```
> > 
> > Discussion at June 27th 2023 WG Call
> > Community open audit until June 30th 2023 at 5 pm ET
> > Decision announced async at 5:01 pm ET
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The issue is not discussed on June 27th 2023 WG Call He made decision before 5:01 pm ET,June 30th 2023
> > We hereby can see how RG trying to use the power of the governance as he wishes. It is clearly an abuse of power.
> 
> I don’t understand what you mean here. This issue contains an LDN with extensive evidence about what happened. There is no debate about this.
> 
> Do you mean that you dispute the evidence given or do you mean that the procedure followed is not correct? What exactly is your role in the T&T working group?

I am asking RG not you. Let him answer first.
About my role, as a community member, and defendant for bq1024.

**Comment by herrehesse** [comment] 2023-07-01 17:00
Arrogance won’t help you with this case I am afraid.

**Comment by claydrone** [comment] 2023-07-01 17:01
> Arrogance won’t help you with this case I am afraid.

let focus on the case and wait @raghavrmadya 's reply to my question.

**Comment by cryptowhizzard** [comment] 2023-07-01 18:02
> to @cryptowhizzard I am asking RG not you. Let him answer first. or follow RG's logic, you are "collusion" with RG? since no need of evidence to claim this.
> 
> About my role, as a community member, and defendant for bq1024.

As notary and member of the T&T working group i kindly asked you to explain what you meant. How do you expect to get appropriate answers when you fail to explain what your question is?

**Comment by claydrone** [comment] 2023-07-01 18:29
> > to @cryptowhizzard I am asking RG not you. Let him answer first. or follow RG's logic, you are "collusion" with RG? since no need of evidence to claim this.
> > About my role, as a community member, and defendant for bq1024.
> 
> As notary and member of the T&T working group i kindly asked you to explain what you meant. How do you expect to get appropriate answers when you fail to explain what your question is?
> 
> The topic is “Based on the signing behavior on the [filecoin-project/filecoin-plus-large-datasets#1938](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1938), the notaries have ignored flags raised by other notaries and are being investigated for abusing DC.”
> 
> This evidence is clear and sufficient. Until now no-one disputed from the T&T working group.

I clearly state that the question is to RG, and want him to answer, I do not expect you to answer and I have the right not to answer your question. If RG wants me to answer, I can answer to him, or you can show proof that you are authorized by him as his speaker.

if you want to discuss the issue about https://github.com/filecoin-project/notary-governance/issues/898, you can go there.

**Comment by cryptowhizzard** [comment] 2023-07-01 18:34
> > > to @cryptowhizzard I am asking RG not you. Let him answer first. or follow RG's logic, you are "collusion" with RG? since no need of evidence to claim this.
> > > About my role, as a community member, and defendant for bq1024.
> > 
> > 
> > As notary and member of the T&T working group i kindly asked you to explain what you meant. How do you expect to get appropriate answers when you fail to explain what your question is?
> > The topic is “Based on the signing behavior on the [filecoin-project/filecoin-plus-large-datasets#1938](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1938), the notaries have ignored flags raised by other notaries and are being investigated for abusing DC.”
> > This evidence is clear and sufficient. Until now no-one disputed from the T&T working group.
> 
> I clearly state that the question is to RG, and want him to answer, I do not expect you to answer and I have the right not to answer your question. If RG wants me to answer, I can answer to him, or you can show proof that you are authorized by him as his speaker.
> 
> if you want to discuss the issue about #898, you can go there.

Thank you for this explanation. However, this Github issue is about a specific topic. If you have off-topic questions to @raghavrmadya i kindly request you to address them in a specific issue, slack or one of the T&T calls.

**Comment by ArthurWang1255** [comment] 2023-07-03 06:00
I think the community should keep in an agnosticism manner. If we can sensor the datasets with ChildPorn / Copyright violations and etc, we can abandon these clients and related notaries. Otherwise, let the code be the law.

**Comment by cryptowhizzard** [comment] 2023-07-03 06:03
> I think the community should keep in an agnosticism manner. If we can sensor the datasets with ChildPorn / Copyright violations and etc, we can abandon these clients and related notaries. Otherwise, let the code be the law.

Without retrieval you can’t.

**Comment by herrehesse** [comment] 2023-07-03 06:25
Do you not realize the significance of the notary role and retrievals? If someone actually stored child pornography on any of these platforms and received datacap for it, it poses a serious issue for everyone involved in this field.

The aforementioned notaries have failed to fulfill their responsibilities adequately, and I strongly recommend their removal as suggested in the recommendation.

**Comment by Carohere** [comment] 2023-07-03 14:35
> We would like to provide some background regarding the application mentioned:
> 
> **Timeline** On May 2, a notary questioned the retrieval problem. On May 4, the client responded that the retrieval process works and provided screenshots. On May 6th, we trigged the checker and confirmed that the Datacap and CID report was in order. After confirming that the notary who had previously raised the issue was aware of the status of the request, we signed the second round of allocation.
> 
> **Our signature** We have confirmed the description, DC usage report, retrieval result, and we definitely considered feedback from other notaries in application #1938. We find it difficult to understand the accusation about "ignored flags raised by other notaries" posed to us.
> 
> As we shared many times before, as a media company we do our best to verify the legitimacy of applications. We value the importance of data and LDN's guidelines. We are dedicated to loading more valuable data into the network. We understand and appreciate that retrieval is an important component of the network. In particular, prior to the launch of retrieval checker, we had several calls for retrieval tutorials in hopes of facilitating notary access with a more visual approach to the data and freeing up the reliance on technical background.
> 
> We are pleased to see the launch of the retrieval checker. It allows everyone to verify the retrieval success rate, a good factor for determining the compliance of applications. With the new function available, we sincerely hope that the governance team can give a clear definition of what kind of sign-off is acceptable and what is not for a clearer environment in Filplus project.
> 
> Best Regards, PangodGroup Team

Hi @Casey-PG, appreciate you taking the time to share all details. Everything checks out except i do share the same concerns as @kevzak mentioned [above](https://github.com/filecoin-project/notary-governance/issues/892#issuecomment-1609934966). Could you share more insights on these questions? 

>As you can see here https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1938#issuecomment-1518947769, @zcfil asked some questions to start to the applicant. There was no answer.

>Who is the applicant? A new member to Filecoin? Or with experience? They must be experienced to be onboarding 1PiB+ per week recently.

>And are they the data preparer? How are they preparing the data?

>And how did the applicant find SPs? Who are the SP businesses involved? Do they have 2-3-4-5 SP groups?

>The applicant mentioned for the question "In which geographies do you plan on making storage deals" - Asia other than Greater China, North America, Europe. But if you look at CID report it seems like 1-2 notaries in China/HK.

>These are all flags when I look at this. And yet, not one of the signing notaries asked any of these types of questions. They just leave comments that are copied and pasted verbatim from other applications.

**Comment by hsxiaotianquan** [comment] 2023-07-04 03:18
> Do you not realize the significance of the notary role and retrievals? If someone actually stored child pornography on any of these platforms and received datacap for it, it poses a serious issue for everyone involved in this field.
> 
> The aforementioned notaries have failed to fulfill their responsibilities adequately, and I strongly recommend their removal as suggested in the recommendation.

@herrehesse 
Why are you talking about illegal things? Can you read everything on filecoin? If the other clients are storing child pornography, can you check them?   

Can you guarantee which notary's signature all will be retrievable? Please list them!   

Are you a notary? Have you ever worked as a notary? If not, please stop your speech and stop attacking the notaries.  

You've thrown the entire fil+ community into chaos. I call on the community to stop your speech.

**Comment by Casey-PG** [comment] 2023-07-04 07:45
@Carohere Thank you for taking a look at our answer and reminding us of questions. This client is a technical professional transitioning from web2. She/he is a DP, formerly worked on slingshot, has a certain knowledge of storage. The client committed to distributing copies to more than eight or more service providers, not limited to Asia Pacific, North America, and Europe regions. 
> > These are all flags when I look at this. And yet, not one of the signing notaries asked any of these types of questions. They just leave comments that are copied and pasted verbatim from other applications.

On the last question, all notaries' sign-offs are based on their own DD rules and presented to the community in a summary on the issue. We did not copy paste other notaries' words, but we understand your point. We have also noticed this phenomenon during our DD in applications. We believe that this results from the great similarity in the criteria that need to be met for notaries' approveal. Hence the similarity of the notary's comments cannot be avoided and it is common that almost all notary's sign-offs are done in the same manner. 

If there are new requests from the community for notary DD feedback, we will comply with the program requirements accordingly. However, I would like to remind that there are privacy concerns for clients if entities have to fully publish all information and time costs for notaries due to the language barrier. We believe this is the same logic as the notary due diligence flow tool on https://filplus.fil.org/ using "action" feature to reflect a quick response.

![image](https://github.com/filecoin-project/notary-governance/assets/107392596/29de54c3-7bdb-431b-99b3-2b36325e5865)

Lastly, we welcome additional comments, but we would like to limit this discussion of #1938 signing only, if it is not specific to the topic of this proposal, we sincerely hope it will take place in other ways.

Best regards,
PangodGroup Team

**Comment by cryptowhizzard** [comment] 2023-07-04 07:56
> > Do you not realize the significance of the notary role and retrievals? If someone actually stored child pornography on any of these platforms and received datacap for it, it poses a serious issue for everyone involved in this field.
> > The aforementioned notaries have failed to fulfill their responsibilities adequately, and I strongly recommend their removal as suggested in the recommendation.
> 
> @herrehesse Why are you talking about illegal things? Can you read everything on filecoin? If the other clients are storing child pornography, can you check them?
> 
> Can you guarantee which notary's signature all will be retrievable? Please list them!
> 
> Are you a notary? Have you ever worked as a notary? If not, please stop your speech and stop attacking the notaries.
> 
> You've thrown the entire fil+ community into chaos. I call on the community to stop your speech.

What a nonsense. Just because you don’t like what someone is saying does not mean it is not valid.

**Comment by The-Wayvy** [comment] 2023-07-07 05:42
Let's gradually decrease the FIL+ multiplier, say, over 5 years, until it's gone.

It's not right for block rewards to be determined by a bureaucracy.

Satoshi would be horrified.

**Comment by cryptowhizzard** [comment] 2023-07-10 08:45
So, where are we with this proposal?

I stumbled today on https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1584

It seems the situation is more then clear here and we need to take action please.

![Scherm­afbeelding 2023-07-10 om 10 44 54](https://github.com/filecoin-project/notary-governance/assets/36404435/c59976da-7b6f-422a-8fff-b7a2fe74d6af)

**Closed** 2023-08-22 14:52 UTC
Labels: Proposal
