### ISSUE TITLE
Discussion: Mechanism of removing DataCap from client and returning it to the notary.

### ISSUE THREAD

**Issue by LandsatFile20** [filecoin-project/notary-governance#119] opened 2021-04-29 01:31 UTC
## Issue Description
1. Clients accidentally lose the private key and could not access DataCaps anymore.
example on  [filecoin-plus-client-onboarding  issue #67  ](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/67)
2. The clients use Datacaps in unethical ways such as excessive self-dealing, data stored unavailable for retrieving, etc.

## Impact
In both scenarios above, DataCaps will not be utilized in a way that aligns with FIP-0003.

## Proposed Solution(s)

Scenario 1: Remove the remaining DataCaps from the address and return the DataCaps to the corresponding notary. The client still can reapply for DataCaps.

Scenario 2: Recycle the remaining DataCaps from the client and return to the corresponding notary. Prohibiting the client to reapply for a period of time, or giving tighter restrictions when the client reapplies.

**Comment by dkkapur** [comment] 2021-05-10 01:08
Thanks @LandsatFile20 for filing this issue. Looks like per the current implementation for the actors in Filecoin, there is not currently a way to do this, so we should look into filing a FIP to support this. Generally, this makes sense to me. I've also been thinking about ways in which the penalizing of "bad" uses of DataCap could be extended to the miner itself receiving unfair rewards in the network. What are your thoughts on this? 

I know @s0nik42 @NSC-FIL have also mentioned support for something similar in prior governance calls, would be interested in hearing their and other's perspectives also!

**Comment by MasaakiNawatani** [comment] 2021-07-12 05:59
Hi everyone, I encountered a similar case and I believe we should file a FIP for this. My client is asking for the same amount of datacap originally requested due to them losing their private keys. It would be interesting if we can have a way to burn the datacap given to that address before we issue a new one.

**Comment by dkkapur** [comment] 2021-12-21 06:08
Closing out this issue - further discussion to continue in https://github.com/filecoin-project/FIPs/pull/226

**Closed by dkkapur** 2021-12-21 06:08 UTC

**Comment by kdreampool** [comment] 2022-02-01 02:14
Am I late?
In case of no confirmed Clients activity or abuse of systems and incentives, the current level of discussion and action is correct.
However, it is often the SP that drives Clients that use Datacap in unethical ways, such as excessive self-transactions, unsearchable data, etc.
Therefore, it is necessary to discuss how to strictly limit these SPs.

For example, the SP concludes that clients without valid data meet the conditions to simply apply for a datacap.
The SP then moves the Clients to either request a DataCap or apply the DataCap application on behalf of the Clients to power on *10 with garbage data.

As discussed so far, there is no limit to these malicious SPs. SP recreates new clients to be used for unethical behaviors such as excessive self-trading and inability to view data.
