### ISSUE TITLE
Discussion: maybe we need a way of defining “notary diversity” in the rubric

### ISSUE THREAD

**Issue by askender** [filecoin-project/notary-governance#74] opened 2021-01-05 18:33 UTC
The challenge is figuring out good objective metrics you can use to draw the lines clearly.
Notice: it is different from Use Case Diversity and Geographic Diversity.

My ideas:
- Notary Application cannot tell everythings about a miner. Maybe there will be a onchain-voting system(Quadratic Voting?) about Notary reputation?    
- If a Notary also has a miner or lots of miners, there are potential relevant benefit. The notary should tell all its related miners.
- Miners with different size of power is thinking about different things. When they become notaries, they have different thoughts too.    
- When a notary/miner have many investors, sometimes they have not free-will.  investors info can be also a objective metric.

Look forward to hearing from you!

**Comment by askender** [comment] 2021-01-08 16:51
Both hardware diversity and reputation matter.

**Comment by jnthnvctr** [comment] 2021-01-12 21:12
Re (1) - I like this idea! Is the thought to make this one of the criteria that factors into the score? 

Re (2) - Do you think it makes sense to maybe expand how we're defining self-dealing to account for this? The goal with the previous phrasing for "affiliated addresses" was intended to try and capture this: https://github.com/filecoin-project/notary-governance/tree/main/notaries#operational-guidelines

Re (3) and (4) - is there a good way of defining different Notary types? Even outside of the miner size, it could be useful to also look for a diversity of Notary types (e.g. more developers / people who have no financial gain altogether).

**Comment by jnthnvctr** [comment] 2021-01-12 21:15
Basically trying back into what a reasonable way of actually defining lines that could be objectively evaluated that we can encode into a rubric

**Comment by jnthnvctr** [comment] 2021-01-18 20:49
Re (3) and (4) - perhaps this is as simple as saying: 
1) One metric of "diversity" is along whether you have any affiliation / financial stake to any mining operations (to delineate between miners / their affiliates and others). 
2) I don't have a good metric for segmenting on size - but it occurs to me that simply prioritizing "neutral" parties may be sufficient? 

I'm not sure how one would be able to define hardware diversity in a non-gameable way... there might be some interesting applications of a community vote that could come into play, but I think we'd need to have some tooling to make that reasonable (and as @zixuanzh  always asks - figuring out a good way to vote is the hard part).

**Comment by askender** [comment] 2021-01-29 14:04
Define hardware diversity in a non-gameable way is hard.     But notarys should report all their related miners and other kinds of mining affiliation themselves at least.

**Comment by jnthnvctr** [comment] 2021-02-01 22:32
Re: disclosure - I agree, we already have something like this in place under the "No self dealing rule" in the Notary attestation - though if there are areas for improvement (or better ways of defining it) we should definitely propose a fix. When originally writing it the aim was to make it relatively general: 

> No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.

**Comment by dkkapur** [comment] 2022-10-07 06:01
Closing this out as it is now relatively out of date. Expecting proposals for additional changes to the rubric now in time for the fourth round of elections. Please feel free to open up a new proposal as you see fit based on this discussion or otherwise.

**Closed by dkkapur** 2022-10-07 06:01 UTC
