### ISSUE TITLE
Notary Application: NDLABS

### ISSUE THREAD

**Issue by NDLABS-OFFICE** [filecoin-project/notary-governance#604] opened 2022-08-25 09:07 UTC
# Notary Application

To apply to be a Fil+ Notary, please review the Notary Overview [here](https://github.com/filecoin-project/notary-governance/tree/main/notaries#overview) and then fill out the following form. 

## Core Information
- Name:Leo
- Affiliated organization:  ND LABS
- On-chain address to be notarized (recommend using a new address): f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
- Region of Operation: [ Asia minus GCN]
- Use case(s) to be supported: General
- DataCap requested for allocation (10TiB - 10 PiB):1PiB

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

### Time Commitment
Describe the nature and duration of your affiliation with the Filecoin project. Please include relevant Github handles, miner ids, significant projects or contributions (with links).
```
ND LABS has technical operation centers and nodes in Singapore, Hong Kong, the United States, and Dubai. Since Fil has launch of the mainnet in 2020, ND has begun to provide technical services to partners to help them complete the construction of storage services. At present, the accumulated storage power of ND exceeds 160P globally. The largest node has 84P storage power, and the node owns exceeds more than 1.4 million FIL. 
ND LABS is positioned as a decentralized storage service provider for WEB3. For a long time, ND not only focuses on building nodes for partners, but also explores how to provide better storage services for potential clients of web3. Since October 2021, ND has been deeply involved in the FilPlus project, vigorously promoting the Filplus project to partners who has effective data storage needs. We also providing them with a complete set of solutions and technical services for storing data in the FIL network. The Singapore and US nodes are the main storage nodes, which was provide real data storage for early customers.
```

### Stake Exposure
Please cite total token at stake (currently available, locked as collateral, vesting over time) and any substantiating evidence.
```
f0152799(329,791.9335fil)、
f01168661(71,800.6255fil)、
f01137150(570,579.5868fil)、
f01715155(28,565.5908fil)、
f01740934(11,930.8110 fil)、
total：1012668.5476 fil
Besides this nodes, the assets we disclose are part of our assets, accounting for 1/6 of our total assets.
```

### In-protocol Reputation
Please describe (in detail) your activity and tenure as a member of the Filecoin community. Please note (with links where possible) any contributions made to implementations of Filecoin, the spec, documentation, or to substantially help the Filecoin ecosystem grow. 
```
https://twitter.com/imNDLABS/status/1501126179512012801
https://twitter.com/imNDLABS/status/1504695558795149321
https://twitter.com/imNDLABS/status/1504159515423363083
https://twitter.com/imNDLABS/status/1503801081704329216
https://twitter.com/imNDLABS/status/1502052551570690050
https://twitter.com/imNDLABS/status/1502047484729831427
https://twitter.com/imNDLABS/status/1501593768067280897
https://twitter.com/imNDLABS/status/1501207713313062912
https://twitter.com/imNDLABS/status/1495731744989126663
https://twitter.com/imNDLABS/status/1478313717016055808
```

### In-protocol Security
Please describe your contributions to the security of Filecoin and the duration over which you've made contributions. Please also include any links or references that can substantiate your contributions. 
```
N/A
```

### Organizational Reputation
Please describe the nature of your organization, including the country of registration, size of the organization, and time since inception.
```
Founded in 2019, ND LABS PTE.LTD. has offices in China, Singapore and America. ND LABS is committed to becoming an enterprise that provides distributed storage infrastructure construction and distributed storage service support for the "the meta-universe".
At present, we are mainly engaged in two business lines:
1. Infrastructure construction of distributed storage. At present, we have set up our own nodes in the United States and Singapore. In the future, we can provide our customers with storage and computing power cooperation services.
2. Distributed storage related software services, including online storage, SaaS services, etc. At present, we have developed a website to help users store effective data online, which is now for promotion and operation. In the future, we will also iterate on the platform and develop our own SaaS storage services.
```

Please share any relevant details to help substantiate information about your organization (website, named officers, links to social media profiles).
```
Twitter：@imNDLABS
```

Please share any relevant external information regarding your organization (e.g. news articles, social media profiles, etc.)
```
https://drive.google.com/file/d/1jZyJeO1Sw2HGwBDQXgEXjRyuytsrRMJH/view?usp=sharing https://drive.google.com/file/d/10Y3Ufml0QxZSUbf3q5itJvz1I8-ymCb5/view?usp=sharing https://drive.google.com/file/d/1-8r7rT3zZsrr1jlZncC4LFUiMwQ-1viJ/view?usp=sharing https://drive.google.com/file/d/1bRcnny0rIALDpgow327mntCjlI7TBIkn/view?usp=sharing https://drive.google.com/file/d/1j2OMawo3B5CT9DuGl-OwF0jukeMrAqxf/view?usp=sharing https://drive.google.com/file/d/13OlsAyp5KAEZDsfcnaqrvz4Xn4gIInbT/view?usp=sharing https://drive.google.com/file/d/1uOAEI1awVXdqdi-t5kRi53RoYSyHyHse/view?usp=sharing https://drive.google.com/file/d/12EWAFbcedk9L2wxKHsRZl5TA3qpf1-md/view?usp=sharing https://drive.google.com/file/d/1jgjMRL0LBNGxH6tRCksDLnPElcBQKhRC/view?usp=sharing https://drive.google.com/file/d/1uShHie9rYnGBPMTMLEkgYYubEZoh5cgl/view?usp=sharing https://drive.google.com/file/d/1x9oCbv_ozVoV6htj3v7Z72SfWvf_pAep/view?usp=sharing https://drive.google.com/file/d/1R0Ae2P19103A9P07FXM-lSTyn-fzr8Hg/view?usp=sharing https://drive.google.com/file/d/1DOIOuPfjsXC0qnl1ksuyU_6hXwoliDRE/view?usp=sharing https://drive.google.com/file/d/1XlGv1w5Eq9knU2Q4IFUgH_VHMkVuFtW0/view?usp=sharing https://drive.google.com/file/d/1Q2vWEBulrSOCz16-OCyYQghfGf5T1fVO/view?usp=sharing https://drive.google.com/file/d/1Gm1alwYuL3_WD-XmFXPm0dWkG9oY-vDk/view?usp=sharing https://drive.google.com/file/d/19P0OxqmL7IXIGw4wBIc1wIlixwubHbLd/view?usp=sharing https://drive.google.com/file/d/1IlUIA_b7BmcrzACX0yeoYsfQnANc7vHB/view?usp=sharing https://drive.google.com/file/d/1mAuuZU9py2S3AdbOeXZ2cXhCY-lg46pr/view?usp=sharing https://drive.google.com/file/d/1z-HXjJMtByMR82wYCnq__S-hSB5yuzTh/view?usp=sharing https://drive.google.com/file/d/1jX53udWAOpKOOvK33nuIHvrb3wGTHtUd/view?usp=sharing https://drive.google.com/file/d/1lYD5JeKQcXTG56U26NJ-_aXJvEC5QlER/view?usp=sharing https://drive.google.com/file/d/1htH1q8aScViFWbLo07ju41v6J8rNSoCR/view?usp=sharing https://drive.google.com/file/d/1YcHS70Q-OmNoxb47ioMNi7XTxrSaqqx7/view?usp=sharing https://drive.google.com/file/d/1VH4AX-PtqU4h052VdeAo0W-0TZP2aoYR/view?usp=sharing https://drive.google.com/file/d/1R1mu42qxXgXvfd3gxx3eNc0_ibJ0Wx4n/view?usp=sharing https://drive.google.com/file/d/1SHzo5V-Aaur0SnyyAcVVnnfzS_QxHwbL/view?usp=sharing)
```

### Individual Reputation
Please share links to at least 2 of your (personal) social media profiles (or accounts that you are able to use) and the approximate size of your audience (i.e., followers, subscribers) for each one.
```
@imNDLABS Followers: 17k
@Vicky777670 Followers: 50k
```

### Use Case Diversity
(Optional) Any additional information you'd like to share about the use case(s) you plan to support?
```
We plan to support the following data:

30%: Video data, including videos related to film and television and surveillance
20%: web3.0 related data, including NFT, gamefi, SocialFi and other data
30%: Relevant data with social contribution, such as e-books, art, etc.
20%: Stored data of ND-related business customers
```

# Allocation Plan
### Allocation Strategy
How do you plan on allocating the DataCap requested above? Please describe your allocation strategy with as much specificity as you can. This includes the target amount per client and rate at which you'll allocate DataCap.
```
We will use the assessment model to score clients, according to the standard scale of 1 to 5 to evaluate and assign their DataCap needs. 
We have made a scoring table for clients reviews :
https://docs.google.com/spreadsheets/d/17h4X9lvE4Sdr47mHiwAJzYyXwtW743KV/edit?usp=sharing&ouid=118364709155675277156&rtpof=true&sd=true

We will assign DataCap to the clients who can provide real information of their company and ensure that the data is publicly available. We have a series of rules to determine the true and valid identity information of clients：

1.We will browse the client's official website to understand the basic information of the their organization.

2.We will require the clients to provide verifiable information such as the organization's business registration and establishment documents by mail

3. We will conduct a review of the clients company's data storage content, and we prioritize the clients who store high-value data.
We will use the assessment model to score clients, according to the standard scale of 1 to 5 to evaluate and assign their DataCap needs. 
We have made a scoring table for clients reviews :
https://docs.google.com/spreadsheets/d/17h4X9lvE4Sdr47mHiwAJzYyXwtW743KV/edit?usp=sharing&ouid=118364709155675277156&rtpof=true&sd=true

We conduct our internal review process through 4 stages
1. The primary reviewer will conduct a basic review of the application submitted by the client. The applicant's data storage must be open and valid data, and there are real storage requirements.
2. According to the results of the basic review, the junior reviewers will submit the allocation process to the intermediate reviewers, and the intermediate reviewers will give a score based on the content of the evaluation model.
3. According to the scoring results of the intermediate reviewers, the senior reviewers will further conduct a detailed investigation of the business ecology of the company, as well as verify the true information of the applicant and the company, and make a final decision and signature.
4. After the decision of the senior reviewer is approved and signed, the DataCap will be assigned a certain amount to the client. If not passed, we will inform the client of the review result.
```

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?
```
We use a hardware wallet to store the private key to ensure the security of the account. After being reviewed by our internal decision makers, the data caps will be allocated to applicants by those who have the right to execute the hardware wallet.
```

### Client Due Diligence
How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them? 
```
In order to ensure the authenticity of the information and reputation of our clients, we will verify the online and physical identity and reputation of our clients through the following content.


Online information:
1.Review third-party public data provided by clients, such as Twitter-type social media accounts. We will observe the activity of the account, and the activity of the Github usage period.
2.Browse clients and their company's official website and review the company's history, news, ecology and products.
3.Make a query on the enterprise information website in the clients country/region
4.Use official email to confirm whether the clients is applying for Data Cap, and confirm their identity information and job information.

Entity Information:
1.We will require our clients to provide business registration, establishment documents, public registration information and relevant certificates.
2.Will require our clients to provide government-issued ID or passport information.
3.Our clients need to provide us with sample data they want to store, and we will check that their data is valid and publicly available.
4.For the privacy of the clients, we will recommend that our clients send entity information by email.

We will require our clients to promise not to have any violations. We will give a reminder if there is any of the following behaviors. The clients with serious violations will be blacklisted by us.

1.We require our clients to comply with the laws of the country and region where they are located, and shall not have any violations of laws and regulations.
2.We require our clients to comply with Filecoin's community regulation..
3.Our clients must ensure the stored content is legal, valid and insensitive.
```

What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.
```
We require clients to disclose transaction information. After the clients obtain Data Cap, we will continue to follow up their transaction information every week. Once the clients are found to have violation operations, we will give a reminder. If the violation circumstances are serious, we will disclose the violating operations of this client in the public community, and pulled into the blacklist to reject the future application. If the client refuses to disclose, we will deny his application.
```

### Bookkeeping Plan
Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both? 
```
Our allocation strategy and auditing process will public on Github to ensure our impartiality.
We will follow the FIL+ guidelines and conduct all our allocation decisions publicly on Github.

filecoin-plus-client-onboarding
filplus.info
```

Where do you plan on keeping a publicly accessible record of all your allocation decisions?
```
We are going to do a google sheet to keep all the work records in relation to our allocation decisions.

The google sheet is an internal database for storing the foregoing files. However, if it needed, we will authorized visitors to access the file.
Besides, without disclosing any confidential information about our clients, we are happy to respond to reasonable inquiries or inquiries that community members may have regarding our DataCap allocation decisions.
```

### Engagement in Program
How much time per week, on average, are you willing to dedicate to participating in the Fil+ program? This includes making DataCap allocations (direct and/or Large Datasets), comments on discussion/issues, attendance in governance calls, messages in Slack, etc.
```
20+ hours per week on average, including  participating in the program and making allocations. i will also attend in governance calls and response messages in slack. 
```

### Past allocation 
Have you previously received DataCap to allocate before? If so, please link to any previous applications.
```
Never had
```

Cumulatively, how much DataCap have you previously successfully allocated? 
```
Never had
```

**Comment by dkkapur** [comment] 2022-09-22 00:23
## Request Approved
#### Address 
>  f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Datacap Allocated
> 1PiB

**Comment by Stoibers** [comment] 2022-09-23 10:23
## Notary Ledger Verified
#### Message sent to Filecoin Network
> message CID: bafy2bzaceblzidu4gt5e5tffbjn5uohashndiafi7o4bel6ir4u4jzngb24wm
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceblzidu4gt5e5tffbjn5uohashndiafi7o4bel6ir4u4jzngb24wm

**Comment by Kevin-FF-USA** [comment] 2022-11-22 21:48
Hello @NDLABS-OFFICE  ,
Thanks for applying to become a Notary in the Fil+ program! 

As we score your application, you will need to verify your contact information and affiliated organization.  Please email NOTARYELECTION@FIL.ORG from the email account linked to this GitHub account. *The email MUST COME from the same account you used in this application. 

Subject Line:  Notary Name, Application Number
Email Body:  
1. Your First and Last name
2. Are you applying as an individual or Organization
3. Your Country of Operation
4. The updated SLA participation Level (https://github.com/filecoin-project/notary-governance/issues/630) 
5. Your Slack handle in [filecoinproject.slack.com](http://filecoinproject.slack.com/)
6. Link to this GitHub application

This step needs to be completed by 28NOV.  Emails received after the 28th run the risk of delaying scoring and may result in your application not being completed.  Once we receive verification of your email, we will then send you a token code to verify and link your SLACK account.

Should you have any questions, please post them here in the comments section of your application and tag @Kevin-FF-USA and @panges2

Thank you!

**Comment by Kevin-FF-USA** [comment] 2022-12-02 18:20
This application looks to be a duplicate of the application for https://github.com/filecoin-project/notary-governance/issues/697. Closing application - if incorrect, please reopen and let me know

**Closed by Kevin-FF-USA** 2022-12-02 18:20 UTC
Labels: Notary Application, Round 4 Notary
