### ISSUE TITLE
Notary Disclosures Tracking

### ISSUE THREAD

**Issue by galen-mcandrew** [filecoin-project/notary-governance#571] opened 2022-07-11 22:44 UTC
## Issue Description
A group of companies that have overlapping relationships with one another have submitted requests to be Fil+ notaries in the third round of elections. At this stage of any new ecosystem, there is bound to be collaboration, shared interests, aligned incentives, and at times mutual investments. It is not unreasonable for a company that invests in web3 projects, for example, to have multiple relationships with teams building in the Filecoin and IPFS space. 

While these kinds of partnerships are reasonable, one of the primary goals of the Filecoin Plus program is to bring a layer of social trust to the network. With that in mind, the governance team strives for transparency, and encourages all of our collaborators to do the same.

Some questions about the amount of overlap and potential or possibility of collusion have been raised. There is also increased concern in this case, where multiple organizations also have large dataset applications open. This could lead to an entity or group of entities acting entirely as clients, notaries, and storage providers, which would be a violation of notary agreements and against the values and intent of the Filecoin Plus program and the DataCap subsidy.

## Proposed Solution(s)
Some questions have been raised directly in the notary applications, as well as on Slack. I would like to consolidate these conversations into a single thread, allow the companies to address the issues, and allow the community to help track the interactions between these organizations.

I propose the companies each explain their role and relationships to one another. They can also list out their owned addresses, and further reiterate their disclosures, as required in the notary application.

> Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship .

With these clearly documented addresses, we would then require that these organizations not act as self-signing notaries for any large datasets or clients, and additionally that the awarded DataCap would not be utilized in deals with their minerID's.

Once the community has sufficient explanation about these organizations and a record trail (for ongoing community audit), then we propose ratifying these applications as Fil+ notaries for the 3rd round of elections.

**Table of addresses**
I suggest these notaries use the following table structure for consistency.

| Organization | Github Handles | Slack Handles | Notary Address  |  LDN Client Address   |  Additional Address Disclosures - Type of Address (ex. minerID, client)   |
| ------------ | -------------- | ------------- | --- | --- | --- |
| Text         | Text           | Text          |  f1...   |  f1...   | f1... - client, f1... - minerID|

### Timeline
- Issue open for community discussion
- Discussion in July 12th Community Governance calls
- Decision announced at July 26th Community Governance calls

### Technical dependencies 
None specifically at this time.

## Risks and mitigations 
Ratifying all these organizations to serve as notaries and placing on the v3 large dataset multisig could allow for misallocations of DataCap, and an abuse of the notary responsibility. The community, other notaries, governance team, and root key holders will be responsible for monitoring the allocations. With the new tooling to remove DataCap from a client, this risk is mitigated.

## Related Issues
**Notary Applications:**

- [ND Labs](https://github.com/filecoin-project/notary-governance/issues/449)
- [POW Power](https://github.com/filecoin-project/notary-governance/issues/447)
- [NFTstar](https://github.com/filecoin-project/notary-governance/issues/444)
- [Bitrise Capital](https://github.com/filecoin-project/notary-governance/issues/443)
- [IPOLLO](https://github.com/filecoin-project/notary-governance/issues/439)

**Relevant Large Dataset Applications**
- [ND Labs](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/109)
- [POW Power](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/89)
- [NFTstar](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/177)
- [Bitrise Capital](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/139)
- [IPOLLO](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/168)

**Comment by galen-mcandrew** [comment] 2022-07-11 22:52
Tagging here:
@NDlabs
@POWPOWER2021
@NFTStar1
@Bitrise2020
@IPOLLO-OFFICIAL

**Comment by Kobayashi-interflex** [comment] 2022-07-13 16:27
As committed in the governance call, here I post my view on this issue.
Frankly speaking, I don’t think it’s a good choice to make ND Labs a notary here.
In the real world, dishonest behaviors will be published and I believe it’s the same for the Filecoin network since it’s some kind of basic ethic and common sense. We should take measures to prevent similar dishonest behaviors, let’s say, one ballot veto or restart the election to evaluate their certification. Notary is a special role in our community, it requires a solid reputation. So, I think ND Labs, are not qualified for a notary in responsibility and reputation, but other roles, SP or investor in the community are open for ND Labs. On the other hand, if ND Labs insist on being a notary or proving their innocence, I’d like to ask them to recover retrieving their history projects for both notaries and the community to check whether there’s something goes wrong. Granting ND Labs a notary is a severe violation of community rules and principles, I’m afraid that if ND Labs make this, there will be more and more copycat to follow their dishonest behaviors and totally destroy our democracy and environment. I believe CW shares the same idea with me.

**Comment by cryptowhizzard** [comment] 2022-07-13 17:14
@galen-mcandrew 

This abuse info is given in the initial slack thread.

https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1654530346802849

Short summary;

50% of datacap stored towards 1 miner.
Deals not retrievable
Miners not pingable.

The question at hand is not the behaviour, as the that is clear. The datacap is not distributed according to the rules. The Q is, was it done intentionally and on purpose. The second Q is that notary’s should be carefully and carry thrust. 

Reading in the thread, seeing the bot’s and fake accounts respond gives me doubts. This behaviour should not be something we want to see.

![A87D9555-63D4-43FF-970C-3171EEC847CF](https://user-images.githubusercontent.com/36404435/178791984-1a16fc88-7acb-4739-ab2c-894af6365f69.png)

**Comment by galen-mcandrew** [comment] 2022-07-13 17:51
@cryptowhizzard thanks for pointing to the thread. 

So re-reading that 97 reply thread (😅 ), seems like there is a lot of "chatter" with two specific salient claims: the number of 'new' and suspicious accounts commenting in support of the approval, and 'dishonest deal making'.

While I agree the accounts are suspicious, I would rather focus on the specific claims of 'dishonest behavior' as it relates to quantifiable chain behavior.

So, it seems like the biggest actual question comes from unretrievable/un-dialable minerIDs and a consolidation of deals? Which specific minerIDs are in question here? My hope is to get specific data-driven evidence to present to the community so that we can make a decision from fact.

**Comment by NDLabs** [comment] 2022-07-13 17:52
Hi @galen-mcandrew , Appreciate if for the proposal! 

I have filled in the content of NDLABS in the form. Please let me know if anything needs to be modified. Thank you!



Here we would like to mention two points. 

First, let me explain the issue of "self-dealing" here, which we described in our LDN application form in early June. 
Due to technical issues, the data that should be sent to other SPs is sent to the wrong node. After obtaining the client's consent, we immediately TERMINATED the wrongly sealed sectors of f01715155 and f01740934. We feel really sorry but THIS IS NOT OUR INTENTION. We accept and have taken responsibility for all damages. 
If community members have their ideas, we are willing to hear more opinions on this issue.

In addition, the discussions over this period have also given us some thoughts on roles as an SP within the Fil+ community.
As an SP, the essential thing we need to do is to store the client's data reasonably. However, For the goal of Fil+ which is to make the network more valuable, we should take the initiative to find clients and recommend more valuable clients to participate in the Fil+ network, rather than just waiting for clients to "place orders" for us.
Part of the "voice" forbids an SP from finding valuable clients to participate in the Filecoin network, which is not helpful for network. 
We welcome any discussion and would love to hear more suggestions to make us better. But we reject malicious "fights." 

Communication and suggestions make us stronger!!

**Comment by Bitrise2020** [comment] 2022-07-14 06:56
Hi,  @galen-mcandrew  I have updated the form.

I would like to confirm here again, is it not allowed for notaries to sign clients who have had an investment or business partnership? 
Do we need to disclose all the LDN addresses of clients with a relationship with us? If it is, does it mean we need to check all the applications to find whether a client that has a partnership with us in advance?

**Comment by NDLabs** [comment] 2022-07-14 08:01
@cryptowhizzard  
Thanks for your discussion. 

The most crucial point is that NDLabs will not hold these five notaries in our pocket. NDLabs has always only acted as a proposer to suggest those partners participate in programs of Filecoin eco. We hope these partners can be treated reasonably. NDLabs can't and won't replace them as notaries, and we reject to be replaced.
This is our first time participating in notary governance. From what we know, a company would also recommend and guide another company to participate in the notary application during the previous notary application period. They also onboarding successfully and made valuable contributions to the eco (This is not an accusation).
Therefore, we believe this is appropriate behavior conducive to expanding ecological boundaries. In addition, after many exchanges with other notaries, we learned that we need to disclose more detailed information as much as possible to make Fil+ more transparent, and we have done so.

**Comment by cryptowhizzard** [comment] 2022-07-14 08:18
@NDLabs @Bitrise2020 

Please check -> https://github.com/filecoin-project/notary-governance/tree/main/notaries

"Upfront Disclosures: Prior to being confirmed as a Notary, Notaries are expected to disclose all relevant addresses which they control, have a financial stake in, or are strongly connected to by other means. For the disclosure, the Notary should state the relevant addresses and the nature of the relationship."

**Comment by Dave906** [comment] 2022-07-15 02:12
There's an update about #89.https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/89#issuecomment-1184675006
Early this day, @Megan618 pointed out #89 had some suspicious behaviors. Can we have @NDLabs to further clarify this situation for us?

**Comment by Dave906** [comment] 2022-07-15 02:43
There's an update about https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/89#issuecomment-1184675006
Early this day, someone pointed out https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/89 had some suspicious behaviors. Can we have @POWPOWER2021 @NDLabs to further clarify this situation for us? I believe sealed data in https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/89 are concerning with @NDLabs

**Comment by Chris00618** [comment] 2022-07-15 13:59
Occupying the quota of other notary candidates by cheating, which is intolerable to the web3 community.

**Comment by NFTStar1** [comment] 2022-07-18 03:36
Hello, @galen-mcandrew 
We have listed our related information, please let me know if you need any other information. thanks.

**Comment by IPOLLO-OFFICIAL** [comment] 2022-07-19 03:37
Hey, @galen-mcandrew 
we have filled out the form with the required information. Please let me know if any changes are needed.
thank you!

**Comment by 1LISA2** [comment] 2022-08-10 12:01
I think the connection between these companies is reasonable in the blockchain industry. Most companies are in a similar situation. Our community doesn't have to limit them too much. It's great that they're willing to disclose the relationship, and we can easily review their path of action. Good to see it!

**Comment by aaronsjx07** [comment] 2022-08-11 10:04
From what I understand, is it impossible for these 5 notaries to sign an LDN at the same time? If they don't, I think it's reasonable. I don't think there are any other concern.

**Comment by llifezou** [comment] 2022-08-11 11:08
We believe that it is reasonable to have a partnership in the WEB3 field. As long as the initial notarization applications are recognized, and these organizations have sufficient explanations and records to track, then approving these applications as notaries is beneficial for building the Filecoin ecosystem.

**Comment by ipfscn** [comment] 2022-08-12 07:09
Two questions here: 
Can you guys guarantee that you have disclosed all relationships? @POWPOWER2021 @NDLabs @NFTStar1 @Bitrise2020 @IPOLLO-OFFICIAL 
What if these five notaries sign their own LDN in the future? Can we revoke their notary qualifications and LDN application?@galen

**Comment by NFTStar1** [comment] 2022-08-12 07:30
Hello, @ipfscn 
Thank you for your reply.
Yes, we have disclosed all relevant information in accordance with the rules and we will continue to make an update on the form if there are any changes in the future.

**Comment by NDLabs** [comment] 2022-08-12 07:39
Hi @ipfscn, thanks for your comment.

We have disclosed not only the relationships with the other 4 notaries but also other companies active in the Filecoin network. 

For this issue, I think we have reached a consensus that I will not act as a self-signing notary for any large datasets or clients.
What do you think? 

> Two questions here: Can you guys guarantee that you have disclosed all relationships? @POWPOWER2021 @NDLabs @NFTStar1 @Bitrise2020 @IPOLLO-OFFICIAL What if these five notaries sign their own LDN in the future? Can we revoke their notary qualifications and LDN application? @galen-mcandrew

**Comment by NDLabs** [comment] 2022-08-12 08:06
> From what I understand, is it impossible for these 5 notaries to sign an LDN at the same time? If they don't, I think it's reasonable. I don't think there are any other concern.

@aaronsjx07 Understand your concern. Same answer as my last reply. We will follow the rules.
Appreciate it your support!

**Comment by Stoibers** [comment] 2022-09-09 10:27
Hi, @raghavrmadya  
ND Labs has filled in the form. (https://hackmd.io/CRrrrdZ9Rqa_NcVsZ2XFiw
) Please let me know if it need to be edited. Thanks!
Long-time discussion has also given us some ideas about our role as a SP in the Fil+ community.
The most fundemental thing we need to do as a SP is to store our clients' data in a reasonable way. The goal of Fil+ is to make the network more valuable, so we should be actively contacting clients and introducing more clients to the Fil+ network instead of  waiting for them to "place orders". While some people come between and prevents SPs from finding valuable clients to participate in the Filecoin network, and this does not help the network at all.

To point out, NDLabs is not going to put these five notaries in our pockets. Acting as a proposer, what we do is recommand  those partners to participate in the Filecoin ecosystem. We expect those partners to be treated equally. ND Labs can't and won't replace them as notaries, and we refuse to be replaced.

This is our first involvement in notary governance. As we know, during the last notary application, one company would also recommend and guide others to participate in the notary application. They got enrolled and made a credible contribution to the Filecoin Ecology (this is not an accusation). Therefore, we consider this to be an appropriate behavior in favor of expanding Ecology's boundaries. Besides, after many conversations with other notaries, we realized that we needed to disclose as much detailed information as possible to make Fil+ more transparent, which we already did. Not only have we disclosed our relationships with 4 other notaries, but we've also disclosed other companies that are active in the Filecoin network. Hopefully, these disclosures will make members of the community more aware of ND's relationships with these entities. In addition, the disclosures will prevent us from acting as a self-signed notary for any large data sets or clients.

The most controversy previously was the relationship between ND and several other companies, which made community members doubt. 
Due to the problem of Github account, we resubmitted our application for notary several days ago. We also tried to contact other 4 companies. However, I'm not sure whether they are willing to resubmit their application or not.

As discussed above, we hope that community members can cast their worries aside.

Finally, we will obey the rules like before. Thanks governance team for following up. If there is anything that requires our cooperation, please let me know!
Thank you all for your support!

**Comment by raghavrmadya** [comment] 2022-09-21 21:52
Commenting for everyone's visibility - Based on no pushback to @Stoibers comment above and community discussion at the governance call, NDLabs will be added to the V3 Multisig today. Their round 3 notary application was impacted by Github flags and they submitted the new application here - https://github.com/filecoin-project/notary-governance/issues/604

If anyone has a concern, please follow-up in this thread

**Closed** 2022-10-21 17:17 UTC
Labels: Proposal
