### ISSUE TITLE
Notary Allocator Application for IPFS Force

### ISSUE THREAD

**Issue by ipfsforcezuofu** [filecoin-project/notary-governance#1034] opened 2023-12-30 03:07 UTC
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue
 IPFS Force

 IPFS Force

f1qzdvspgxc4wjrfiq4a4ig3rpdlvkl6rgm3voyvy

PRC

Greater China Region (GCR)

Manual

300PiB

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"):2. 
4. Organization Name:
5. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): 
6. Country of Operation (Where your organization is legally based): 
7. Region of Operation (What region will you serve?): 
8. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): 
9. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB):

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Kevin-FF-USA** [comment] 2023-12-31 00:17
Hi @ipfsforcezuofu 
Wanted to let you know this application has been received along with the Airtable detailed answers - the public answers will be posted in a thread below soon. If you have any questions - please let me know.

**Comment by Filplus-govteam** [comment] 2024-01-13 17:10
### Basic Information
**1. Notary Allocator Pathway Name:**
IPFSForce

**2. Organization:**
IPFSForce

**3. On Chain Address for Allocator:**
f1qzdvspgxc4wjrfiq4a4ig3rpdlvkl6rgm3voyvy

**4. Country of Operation:**
PRC

**5. Region(s) of operation:**
Greater China

**6. Type of Allocator:**
Manual

**7. DataCap requested for allocator for 12 months of activity:**
300 PIB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?:**
We propose that a fee be charged to a client for DataCap application. The fee will go into a public fund that can be used to improve customer service and engagement. The notaries who perform particularly well can be rewarded with a bonus from this fund. It will also allow us to allocate more resources to customer service and compliance checks.

**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack.:**
Acknowledge
### Client Diligence
**10. Who are your target clients?:**
Enterprise Data Clients

**11. Describe in as much detail as possible how you will perform due diligence on clients.  If you are proposing an automated pathway, what diligence mechanism will you use to determine client eligibility?:**
In general, the higher the DataCap thresholds are, the more restricted the client scrutiny would be. The ""Know your client"" (KYC) service will be used for some clients with high DC demands.

All clients have to go through a strict process to be qualified in the early stage. Firstly, the information collected from client including:  
1. Entity Information
 - Formation documents: includes certificates of registration/incorporation/information
 - government-issued identification number for the entity
2. Authorized Signatory Information
 - evidence of the authorized signatory's authority to act on behalf of the application entity (evidence include written consent of the company board of directors, or a secretary's certificate, a signed letter from the applicant's CFO, or may be included in the company operating agreement); 
 - close-up photo of the signatory's face next to the visible passport or other government-issued photo-bearing ID
3. Beneficial Owners
If there are any 25%+ shareholders, we need a document, such as a capitalization table, operating agreement, or similar to verify the ownership, and also the following information for each of them: 
	 - legal name;
	 - date of birth; 
	 - street address (P.O. box number is not acceptable); 
	 - a government-issued identification number, which shall be either an SSN, ITIN, passport number and country of issuance, alien identification card number, or number and country of issuance of any other government-issued document evidencing nationality or residence; 
 	- a copy of an unexpired passport or other government-issued document evidencing the individual's nationality or residence which bears a photograph of the individual. 

With this provided information, an interview and data source checking process need to go through. After that, an agreement should be signed for the next step: gradually allocate DataCap and let the client gather more credit.

**12. Please specify how many questions you’ll ask, and provide a brief overview of the questions.:**
Question for clients:
1. Introduction of yourself/ your organization(with links)
2. Use case
3. Location
4. Max DataCap Allocation
5. Filecoin address
6. Miners you intend to allocate DataCap with allocation proportion
7. Specific requirement of miners and storage service
8. For-profit or not

**13. Will you use a 3rd-party Know your client (KYC) service?:**
The KYC will be leveraged on some key clients to verify their identity and perform due diligence. The RFP will be published in the relevant markets shortly after the approval of this proposal. The process and material for the verification or audit will be agreed with the service partner at a later stage. The template mentioned in the previous question will be adapted to the scope of the KYC service.

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral):**
It will be opened to all clients from the GCR region.

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?:**
Glif and filplus.info are useful tools for tracking the distribution of DataCap.
### Data Diligence
**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmit:**
Acknowledge

**17. What type(s) of data would be applicable for your pathway?:**
Public Open Dataset (Research/Non-Profit), Public Open Commercial/Enterprise, Private Commercial/Enterprise, Private Non-Profit/Social Impact

**18. How will you verify a client’s data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?:**
Client is obliged to provide the proof of the data ownership. Based on the client’s assertion, we will randomly verify the data ownership by checking the content. If the content is beyond our knowledge, KYB will be leveraged for further verification.

**19.  How will you ensure the data meets local & regional legal requirements?:**
Client is obliged to provide the proof of the data ownership. Based on the client’s assertion, we will randomly verify the data ownership by checking the content. If the content is beyond our knowledge, KYB will be leveraged for further verification.

**20. What types of data preparation will you support or require?:**
We will guide the clients through the entire process of data preparation and integration. For even more professional support, we will recommend the tool Droplet and its experts to our clients.

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?:**
We will guide the clients through the entire process of data preparation and integration. For even more professional support, we will recommend the tool Droplet and its experts to our clients.
### Data Distribution
**22. How many replicas will you require to meet programmatic requirements for distribution?:**
5+

**23. What geographic or regional distribution will you require?:**
3+ regions  (NA, EU, Asia)

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?:**
5+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?:**
The percentage of distribution for the clients to their different SPs may vary depending on data type, storage performance, and/or operating cost etc. We will use a template to plan, review, and track the DC usage with clients. 

**26. What tooling will you use to verify client deal-making distribution?:**
CID Checker Bot,  filplus.info

**27. How will clients meet SP distribution requirements?:**
As we have already experienced as Notary for 4 years, our SPs rarely have special distribution requirements. Usually, our clients can upload the data to SPs manually or via SP’s platform upon the agrement between them.  

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?:**
Basically, the VPN is not accepted for SPs to provide services to clients. However, an authorization procedure will be introduced to grant temporary authorization in some exceptional cases. VPN usage will be recorded and reviewed at regular intervals. And some permissions will be adjusted as the environment changes.
### DataCap Allocation Strategy
**29. Will you use standardized DataCap allocations to clients?:**
Yes, standardized

**30. Allocation Tranche Schedule to clients::**
First:     1/16
• Second:   1/8
• Third:    1/4
• Fourth:   9/16
• Max per client overall: 5 PiB

**31. Will you use programmatic or software based allocations?:**
No, manually calculated & determined

**32. What tooling will you use to construct messages and send allocations to clients?:**
filplus.fil.org， Venus

**33. Describe the process for granting additional DataCap to previously verified clients.:**
The review and approval process for additional DataCap will be triggered when the remaining DataCap is less than 20%. We are considering an automated tool to grant additional DataCap if the incremental demand is stable and the tool fulfills the requirement.

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • disput:**
client discoverability & applications：
bigdataexchange.io
Community
Offline
filplus.storage
Github
• due diligence & investigation
qcc.com
Official Website
Social Medium
Offline
• bookkeeping
TBD
• on-chain message construction
Venus CLI
• client deal-making behavior
Venus CLI
filecoin.tools
• tracking overall allocator health
 filplus.info
datacapstats.io
• dispute discussion & resolution
Github proposal
Slack Channel
• community updates & comms *
Address all the tools & software platforms in your process.
Slack
Wechat
Telegram
Github
### Tools and Bookkeeping
**35. Will you use open-source tooling from the Fil+ team?:**
Retrieval Checker Bot CIDChecker Bot datacapstats.io filplus.storage filecoin.tools

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?:**
Multiple files will be created in Cloud Notes and/or Google Docs for bookeeping. Each file will contain different level of information for sharing. The file that can be shared to public will be published in the community. Others that are shared to Fil+ Governance or audit team will be published through the appropriate channels. Strict compliance will be followed for all sharing.
### Risk Mitigation, Auditing, Compliance
**37. Describe your proposed compliance check mechanisms for your own clients.:**
We will work with Fil+ Governance Team to refine the compliance check process based on the new pathway. The KYC will continue to be leveraged on client’s compliance check in any changes of entity. We will focus the compliance check on data. However, KYC may also be asked to assist if the compliance check exceeds our capbility or capcity. If any compliance issue is identified during the audit, the next batch of DC tranche will be withheld until the issue is fully resolved. 

Every week, the tool Glif and filplus.info will be used to check whether LDN is distruted as sheduled. Summary reports will be tracked and reviewed based on the information from the tools.  And if needed, improvement plan will be proposed and implemented. 
Execution of the function will be terminated immediately if more than two exceptions are detected during the distribution process.

**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.:**
All allocation decisions will be guided by the rubric publicly on Github.  
Since all interactions are intended to occur publically, most allocation decisions should be self-explanatory. 
Any challenges raised regarding allocation decisions should be discussed publicly, e.g., the Github repo.
If convincing justifications can't be given by the Notary, a dispute resolution application can be filed to the Notary Governance after 14 calendar days since its original challenge date. 
Once the dispute resolution application is filed, the Notary Governance can assign an arbitrator among the Root Key Holders in order to resolve the dispute. 
Depending on the arbitrator's decisions, a hearing may be given within 30 calendar days of the dispute resolution application. 


**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.:**
To ensure high efficiency and transparency, we will use social media and the online community to announce the updates and openly discuss their consequences.

**40. How long will you allow the community to provide feedback before implementing changes?:**
Several communications will be proposed to the community to highlight the changes, solicit their input and then refine the proposal. The entire process will take about 6 weeks before the proposal is finanlized.  

**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?:**
Allocator will utilize Ledger wallet to structure and secure the address.

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?:**
We propose to deploy a smart contract for the DataCap distribution program. It will transfer the fee based on the size of distribution from the client to a public fund pool. Our organization is able to develop and deploy this smart contract. 
### Monetization
**43. Outline your monetization models for the services you provide as a notary allocator pathway.:**
Each time clients are granted the DataCap, they will be charged a fee based on the size of distrubtion. The price will be determined later. The fee will go into a public fund pool managed by the allocator and visible to the community. And it will be used for third-party KYC verification and audit services, client engagement incentive programs, and our additional resources for the services.

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.:**
Our organizational structure consists of development, operation, marketing, and customer service. More than 70% of the team members are technicians. And most of them focus on the projects related to Filecoin. In 2024,  we will continue to allocate more resources to builde Filecoin ecosystem. And we are committed to dedicating sufficient resources to the DC Allocator program as we understand it is essential to the success of Filcoin.

**45. Where will accounting for fees be maintained?:**
All the transactions of fee will be maintained in Fil+.
### Past Experience, Affiliations, Reputation
**46. If you've received DataCap allocation privileges before, please link to prior notary applications.:**
YES The 1st round: - https://github.com/filecoin-project/notary-governance/issues/14 The 2nd round: - https://github.com/filecoin-project/notary-governance/issues/158 The 3rd round: - https://github.com/filecoin-project/notary-governance/issues/412 The 4th round: - https://github.com/filecoin-project/notary-governance/issues/667

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.:**
IPFS Force started in May 2017, is a technical team dedicated to decentralization storage with the vision of building Web3 infrastructure, based in Shanghai, China.  IPFS Force has been sponsored by Shanghai Kunyao Network S&T Co., Ltd. since Kunyao was set up in July 2018 as a company.   IPFS Force regularly conducts meetups and events and supports the industry in developing applications, contributing to the Filecoin ecosystem, and providing technical services.  Currently, IPFS Force has nearly 100 core members and hundreds of thousands of participants in hosted events via on-site or online events.

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?:**
We anticipate that the total DataCap distributed to SPs in 2024 will exceed 3EiB. With the 10% market share in 2023, we estimate that the DataCap in 2024 should be no less than 300 PiB  to meet our clients demand.

**Comment by galen-mcandrew** [comment] 2024-03-18 04:11
## Datacap Request for Allocator
#### Address
> f23ex4ojevlypxnbjc6kbqjgulqcqtrf4ztjblaqy
#### Datacap Allocated
> 5PiB

**Comment by galen-mcandrew** [comment] 2024-10-15 07:15
## Datacap Request for Allocator
#### Address
> f23ex4ojevlypxnbjc6kbqjgulqcqtrf4ztjblaqy
#### Datacap Allocated
> 5PiB

**Comment by galen-mcandrew** [comment] 2024-12-06 06:38
## Datacap Request for Allocator
#### Address
> f23ex4ojevlypxnbjc6kbqjgulqcqtrf4ztjblaqy
#### Datacap Allocated
> 5PiB

**Comment by galen-mcandrew** [comment] 2024-12-12 18:12
Approval: bafy2bzacedjdukz456zqaxu2ipyyogrvohmvz45a4r56ypsnvxfvhbosbxkpw

**Closed by galen-mcandrew** 2024-12-12 18:12 UTC
Labels: Notary Application, ready to sign, Round 5 - Allocator, start sign datacap
