### ISSUE TITLE
[DataCap Removal Proposal] Abusive Behaviour Detected on 1947, 1948 and 2045

### ISSUE THREAD

**Issue by herrehesse** [filecoin-project/notary-governance#917] opened 2023-07-06 12:09 UTC
## Issue Description

Multiple instances of abusive behaviour has been identified involving lack of distribution and most likely self-dealing. On every LDN between 50 and 100% of the data is stored at the same entity.

## Impact

This organisation has the capability to accumulate datacap exclusively for its own miners, disregarding regional distribution and engaging in significant self-dealing. Such actions contradict the rules and guidelines of the Filecoin+ program, granting them undue financial advantages over entities striving to operate fair and decentralised storage provider businesses.

## Details

**Clients**

ID | Link | Title | Client | Funding Wallet
-- | -- | -- | -- | --
1947 | https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1947 | [DataCap Application] Radio telescope——National Radio Astronomy Observatory(1/6) | nicelove666 | f1uima5zgx7b2jn7grbkeyvct5ur575cohkpo3lvi
1948 | https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1948 | [DataCap Application] Radio telescope——National Radio Astronomy Observatory(2/6) | nicelove666 | f173fr6nvdhmw5mau4iqlcs3nzt3smnhnzdjoukqq
2045 | https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2045 | [DataCap Application] Radio telescope——National Radio Astronomy Observatory | nicelove666 | f1y5mkyvzsfxsapuecbbs4hrrmio2te6ajdqpgedq

**Storage Providers**

Storage Provider | Client | IP Address | Name | Location | VPNresults | % Sealed
-- | -- | -- | -- | -- | -- | --
f0427989 | f02197473 | 119.167.140.133 |   | CN , Shandong , Qingdao | FALSE with fraudscore 0 | 6
f02182743 | f02197473 | 203.86.113.4 | ipfsfy.com | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 7
f02182798 | f02197473 | 203.86.113.5 | ipfsfy.com | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 7
f02182802 | f02197473 | 87.254.31.140 | ipfsfy.com | GB , England , Newbury | TRUE with fraudscore 75 | 7
f02182867 | f02197473 | 23.224.36.33 | ipfsfy.com | US , California , Los Angeles | TRUE with fraudscore 75 | 6
f02182902 | f02197473 | 210.87.202.191 | ipfsfy.com | KR , Seoul-teukbyeolsi , Seoul | TRUE with fraudscore 70 | 12
f02125861 | f02197473 | 183.178.170.141 | ipfsfy.com | HK , Central and Western District , Central | FALSE with fraudscore 0 | 5
f02182907 | f02197473 | 23.224.22.252 | ipfsfy.com | US , California , Los Angeles | TRUE with fraudscore 94 | 9
f02201915 | f02197473 | 183.220.36.20 | collen - f01939387 | CN , Sichuan , Chengdu | FALSE with fraudscore 0 | 1
f02145020 | f02197473 | 14.29.124.48 | SXX Futuredata | CN , Guangdong , Shenzhen | FALSE with fraudscore 0 | 9
f02085528 | f02197473 | 221.178.58.133 |   | CN , Chongqing , Chongqing | TRUE with fraudscore 70 | 1
f02199203 | f02197473 | 116.136.130.130 |   | CN , Nei Mongol , Ordos | FALSE with fraudscore 0 | 2
f02220982 | f02197473 | 120.232.213.47 | ipfsfy.com | CN , Guangdong , Guangzhou | TRUE with fraudscore 70 | 1
f02105219 | f02197473 | 120.232.213.47 | ipfsfy.com | CN , Guangdong , Guangzhou | TRUE with fraudscore 70 | 1
f02101475 | f02197473 | 203.208.141.101 | ipfsfy.com | HK , Central and Western District , Central | FALSE with fraudscore 0 | 12

Storage Provider | Client | IP Address | Name | Location | VPNresults | % Sealed
-- | -- | -- | -- | -- | -- | --
f02105219 | f02203245 | 120.232.213.47 | ipfsfy.com | CN , Guangdong , Guangzhou | TRUE with fraudscore 70 | 5
f021255 | f02203245 | 61.155.145.100 |   | CN , Jiangsu , Suzhou | TRUE with fraudscore 70 | 1
f02145020 | f02203245 | 14.29.124.48 | SXX Futuredata | CN , Guangdong , Shenzhen | FALSE with fraudscore 0 | 10
f0427989 | f02203245 | 119.167.140.133 |   | CN , Shandong , Qingdao | FALSE with fraudscore 0 | 2
f02204960 | f02203245 | 14.29.124.48 | SXX Futuredata | CN , Guangdong , Shenzhen | FALSE with fraudscore 0 | 4
f02125861 | f02203245 | 183.178.170.141 | ipfsfy.com | HK , Central and Western District , Central | FALSE with fraudscore 0 | 4
f02182867 | f02203245 | 23.224.36.33 |   | US , California , Los Angeles | TRUE with fraudscore 75 | 3
f02182902 | f02203245 | 210.87.202.191 |   | KR , Seoul-teukbyeolsi , Seoul | TRUE with fraudscore 70 | 7
f02182907 | f02203245 | 23.224.22.252 |   | US , California , Los Angeles | TRUE with fraudscore 94 | 7
f02200472 | f02203245 | 171.93.112.10 | ipfsqy.com | CN , Sichuan , Yibin | FALSE with fraudscore 0 | 6
f02422 | f02203245 | 116.169.53.122 |   | CN , Sichuan , Chengdu | FALSE with fraudscore 0 | 10
f02085528 | f02203245 | 221.178.58.133 |   | CN , Chongqing , Chongqing | TRUE with fraudscore 70 | 1
f02101475 | f02203245 | 203.208.141.101 | ipfsfy.com | HK , Central and Western District , Central | FALSE with fraudscore 0 | 11
f02217602 | f02203245 | 203.86.113.6 | ipfsfy.com | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 13
f02217442 | f02203245 | 203.86.113.7 | ipfsfy.com | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 13

Storage Provider | Client | IP Address | Name | Location | VPNresults | % Sealed
-- | -- | -- | -- | -- | -- | --
f02217602 | f02224404 | 203.86.113.6 | ipfsfy.com | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 38
f02217442 | f02224404 | 203.86.113.7 | ipfsfy.com | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 38
f02101475 | f02224404 | 203.208.141.101 | ipfsfy.com | HK , Central and Western District , Central | FALSE with fraudscore 0 | 23

**Notaries**

1Chuangshi1
1igoovo
1stcouldlisa
1zcfil

1a1991car
1Aaron01230
1igoovo
1luobin544
1nj-steve
1Normalnoise
1sxxfuture-official
1zcfil

1a1991car
1Aaron01230
1Bitrise0111
1DaYouGroup
1igoovo
1kernelogic
1laurarenpanda
1newwebgroup
1nj-steve
1psh0691
1Tom-OriginStorage

## Proposed Solution(s)

We propose the following actions to address the situation:
- Immediately eliminate the remaining datacap granted to the client.
- Initiate disputes against notaries who have signed inappropriately.
- Immediate removal of repeated offending notaries from the multisig.
- Blacklist the storage providers implicated in the incident.

### Timeline

Discussion at July 11th 2023 WG Call
Community open audit until July 14th 2023 at 5 pm ET
Decision announced async at 5:01 pm ET

## Additional

Total amount of DataCap being requested 27PiB while the expected size of single dataset (one copy) is only 1P.

**Comment by kernelogic** [comment] 2023-07-07 06:10
I signed according to this CID report. I don't know the relationships on these SP nodes and by looking at them they are distributed in different cities. I don't consider I did anything inappropriately.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1948#issuecomment-1605269236

**Comment by herrehesse** [comment] 2023-07-07 06:47
@kernelogic, Based on the currently available information from the CID checker, I understand your explanation. It is understandable that you were unaware of the situation. 

I would like to inform you that our new abuse tool possesses advanced capabilities beyond what the CID report indicates, which enhances our ability to detect instances of abuse more efficiently.

**Comment by kernelogic** [comment] 2023-07-07 06:50
Is it OpenAI powered?😎

**Comment by nicelove666** [comment] 2023-07-10 10:52
Sorry, it seems we didn't quite understand what you meant. @herrehesse

**Comment by nicelove666** [comment] 2023-07-10 11:16
The reason we are responding so late is because we have identified:

1. SP is independent and belongs to different companies

2. sp does not use VPN

3. The computer rooms of the different sps you mentioned are in different places, and they don't use vpn either.

For example, f02105219 is an sp from Guangdong, China. They don’t use any vpn. This is their first time joining FIL+. They don’t have any fraud, but you show “ipfsfy.com”.


For example, f02125861 is a SP in Hong Kong, and they don't use any vpn, but you show "ipfsfy.com".


I asked the sp you listed and the sp has absolutely no idea what "ipfsfy.com" is or what ipfsfy.com does, the ipfsfy.com website doesn't even open.

I protest the baseless accusation.

**Comment by nicelove666** [comment] 2023-07-10 11:26
You think that all the sps using "ipfsfy.com" belong to the same group.

According to your logic, ipfsfy.com is developed by a Filecoin company, so the sp of this company uses products developed by its own company. Excuse me, do you think it is possible?

Please be careful! For example, you can observe 500 sps, and you will find that there may be 120 sps that use "ipfsfy.com". Excuse me, do these 120 sps belong to the same group?

Please don't accuse us for no reason. It is very easy to accuse, but it is very easy to make people sad,  I believe your actions are out of goodwill, you love Filecoin, and we also love Filecoin, so there is no need to hurt each other!

**Comment by cryptowhizzard** [comment] 2023-07-10 11:38
> You think that all the sps using "ipfsfy.com" belong to the same group.
> 
> According to your logic, ipfsfy.com is developed by a Filecoin company, so the sp of this company uses products developed by its own company. Excuse me, do you think it is possible?
> 
> Please be careful! For example, you can observe 500 sps, and you will find that there may be 120 sps that use "ipfsfy.com". Excuse me, do these 120 sps belong to the same group?
> 
> Please don't accuse us for no reason. It is very easy to accuse, but it is very easy to make people sad, I believe your actions are out of goodwill, you love Filecoin, and we also love Filecoin, so there is no need to hurt each other!

I will show my evidence to the T&T governance board if requested.
Let me remind you that some people did KYC and provided us with the names of SP's they are working with. 

Secondly, most funding addresses trace back to one wallet, evidently one owner.

Thirdly, all machines are on the same port, evidently controlled by one organization. The chances are 1 in 65.000 to the power of the number of miners you have on this identical port that this is a hit. Ie. walking next to an open window is a bigger risk ;-)

Cheers,

-C

**Comment by nicelove666** [comment] 2023-07-10 11:40
Please give evidence now.

I want to see how your evidence makes a falsehood look like a fact.

**Comment by nicelove666** [comment] 2023-07-10 11:41
Filecoin is a community-governed organization and an open platform. You don't need to chat with anyone privately, you just need to communicate on GitHub and show the evidence.

**Comment by nicelove666** [comment] 2023-07-10 11:42
Finally, dear ones, I tell you again very very very firmly that they are not part of the same organization and I am sure I am telling the truth!

**Comment by herrehesse** [comment] 2023-07-10 11:43
@nicelove666 Your strong and defensive reaction only serves to confirm your awareness of the wrongdoing you have been involved in. The evidence against you is overwhelming. Prepare yourself for tomorrow's Trust and Transparency FIL+ call, where we will address this matter in full detail.

**Comment by nicelove666** [comment] 2023-07-10 11:44
We can participate in RG meetings, really, dear, you don't have to be aggressive, don't always think you have the language advantage

**Comment by cryptowhizzard** [comment] 2023-07-10 11:44
Nr1. i am not on your payroll and i am certainly not giving in to any of your "demands".

But yeah , here you can see how stupid it is to put all machines on port 16188. 

![Scherm­afbeelding 2023-07-10 om 13 42 04](https://github.com/filecoin-project/notary-governance/assets/36404435/40464d17-f9bf-4b91-91e1-2db2743762e5)

**Comment by nicelove666** [comment] 2023-07-10 11:45
16188 in China, the homonym is "all the way to send hair", Chinese people like the number 6 and 8.

**Comment by cryptowhizzard** [comment] 2023-07-10 11:46
> 16188 in China, the homonym is "all the way to send hair", Chinese people like the number 6 and 8.

Yes. In Disney the have vacancy's open for story tellers, however, let's focus on the real data.

**Comment by herrehesse** [comment] 2023-07-10 11:46
That is odd @nicelove666, we have measured over 1000 Chinese miners and you where the only one on this port. Coincidence? 

To all other abusive entities contemplating changing miner ports in an attempt to evade detection, be aware that we have a snapshot of the current state. Your efforts to manipulate the system will not go unnoticed, so don't waste your time.

**Comment by nicelove666** [comment] 2023-07-10 11:47
You can observe a few more nodes, Mainland China, Hong Kong, and even many nodes from China to Europe and Singapore all like to use these.

**Comment by nicelove666** [comment] 2023-07-10 11:48
I can't watch you call black white, so I have to contradict you.

Before my initial reply, I have already told you that I have confirmed with the sp, they belong to different addresses, different computer rooms and companies.

If I wasn't sure, I wouldn't contradict you.

**Comment by herrehesse** [comment] 2023-07-10 11:50
I always trust my daughter when she tells me "I did not eat that cookie".

**Comment by nicelove666** [comment] 2023-07-10 11:50
In fact, you have a tool to identify whether the sp uses a vpn, so please use your tool and speak with facts

**Comment by cryptowhizzard** [comment] 2023-07-10 11:51
> You can observe a few more nodes, Mainland China, Hong Kong, and even many nodes from China to Europe and Singapore all like to use these.

Stop selling banana's.

I have 13991 miners logged in my database. 28 are on 16188, all in the subnet's provided above.

![Scherm­afbeelding 2023-07-10 om 13 49 54](https://github.com/filecoin-project/notary-governance/assets/36404435/a755fecc-c640-4d09-903c-2616262ce7c6)

**Comment by nicelove666** [comment] 2023-07-10 11:51
“For example, f02105219 is an sp from Guangdong, China. They don’t use any vpn. This is their first time joining FIL+. They don’t have any fraud, but you show “ipfsfy.com”.

For example, f02125861 is a SP in Hong Kong, and they don't use any vpn, but you show "ipfsfy.com".”    Just use these two nodes for testing.

**Comment by nicelove666** [comment] 2023-07-10 11:52
> 

So you think these 28 are all from the same sp. May I ask, does your company have 28 sps? Who do you think has such great ability?

**Comment by herrehesse** [comment] 2023-07-10 11:52
@nicelove666 It is in your best interest to discontinue your engagement. @cryptowhizzard has provided undeniable evidence, multiple times over, yet you persist in responding as if you are the one being wronged, when the evidence clearly points otherwise.

**Comment by nicelove666** [comment] 2023-07-10 11:53
I also provided evidence, why don't you see my evidence

**Comment by nicelove666** [comment] 2023-07-10 11:54
> > 
> 
> 所以你认为这28个都来自同一个sp。请问你们公司有28个sp吗？你觉得谁有这么大的能力呢？

RG, I know, you can detect that sp uses vpn, just use these two to detect, thank you! @raghavrmadya

**Comment by cryptowhizzard** [comment] 2023-07-10 11:54
> I also provided evidence, why don't you see my evidence

There isn't any except for a fairytale about people loving numbers 6 and 8.

Now if you excuses me .....I really have work to do. If you want to dispute the evidence please go ahead. If you want to join the T&T governance call , do so by all means.

**Comment by nicelove666** [comment] 2023-07-10 11:55
> “例如，f02105219 是来自中国广东的 sp。他们不使用任何VPN。这是他们第一次加入FIL+。他们没有任何欺诈行为，但你显示“ipfsfy.com”。
> 
> 例如，f02125861是香港的SP，他们不使用任何VPN，但你显示“ipfsfy.com”。 

RG, I know, you can detect that sp uses vpn, just use these two to detect, thank you! @raghavrmadya

**Comment by nicelove666** [comment] 2023-07-10 11:56
@cryptowhizzard That's it, waiting for rg to reply, thanks, no need to be noisy, everyone is busy

**Comment by herrehesse** [comment] 2023-07-16 11:00
I kindly request the removal of this client and the remaining datacap. Despite several accusations, no evidence has been provided against it. There has been no progress, so I urge you to take appropriate action.

I also recommend initiating a dispute or removal process for the notaries involved, as it appears that a significant portion of them are recurring abusers (see open issues).

**Comment by nicelove666** [comment] 2023-07-18 03:02
I reiterate that these sps do not belong to the same group, and I have given my reasons:

Logically speaking, if the SPs belong to the same group, which group has this strength and has so many SPs?

In fact, if the SP uses a VPN, there are tools that can detect it. At the same time, I also gave a few nodes, but, obviously, they did not use a VPN, so why do you keep asking, just for the sake of Make all LDNs die?

Finally, I can give our attitude. We can not cooperate with controversial SPs, such as SPs that cannot solve retrieval problems.

**Comment by raghavrmadya** [comment] 2023-07-19 13:37
Seeing continued active discussion on this issue, the T&T WG isn't able to form a conclusive opinion yet with regard to DC removal for the proposed LDNs at this time

**Comment by nicelove666** [comment] 2023-07-20 11:24
Thank you for RG, we have explained it many times, it is pointless to argue back and forth, I hope you can trust us, your trust is very important to us.
Plus, we've never been people who rely only on "words", we like to speak with actions:

First, we will no longer cooperate with SPs that use the "16188" port, and we will confirm their ports with the SP before cooperation.

Second, we promise that among the partners of 2045, there are 2 SPs that cannot be retrieved. Although they have been repairing all the time, they have not been successfully repaired. For this, we will not cooperate with the 2 SPs that cannot solve the retrieval problem. It is not that we will not cooperate with them temporarily, but we will never cooperate with them.

The power of action is more useful than words, and we look forward to your resolution of disputes for us.

**Comment by nicelove666** [comment] 2023-07-22 03:47
The controversy has been going on for a long time. In this regard, in order to communicate more efficiently, we hope to participate in the Trust meeting @raghavrmadya ，and， we saw that you posted about next Tuesday's meeting, so if it's convenient, can we make an appointment on the phone，Your reply is very important to us, thank you for taking the time to communicate with us.

**Comment by nicelove666** [comment] 2023-07-24 15:56
We have repeated, explained back and forth more than 10 times.
https://github.com/filecoin-project/notary-governance/issues/917#issuecomment-1628810081
https://github.com/filecoin-project/notary-governance/issues/917#issuecomment-1639236836

Do you know which port is the most selected, the most selected port should be 6789, lotus, the most selected interface should be 1234, in the miner the most should be 2345. so, Please list the data of boost 6789, there should be more than 200 SPs, then, do you think these SPs belong to the first group?

Your accusations are full of holes, maybe, you can find those LDNs that are really problematic instead of staring at us.

If you keep making trouble for no reason, I will send the contract to RG. I always believe that RG is fair and understands us.

**Comment by nicelove666** [comment] 2023-07-25 12:06
Hey, RG, very happy to be able to participate in the trust meeting tonight, looking forward to the communication at the meeting tonight, considering the limited time of the meeting, now, let us discuss more content and publish all the facts, so that you and the Filplus-govteam can make informed decisions in the meeting.

Let's review the community's doubts about us. The community believes that 50% to 100% of our LDN's data is stored in the same entity. In this regard, they raised two detailed doubts:

1. The SP using port 16188 is from the same company
2. The SPs we cooperate with accept FIL from the same wallet address

Now, let's face facts.

Regarding allegation one:

In fact, the SP using port 16188 comes from many different companies.

As LDN applicants and technical leaders, we will communicate with about 6-10 SPs before each LDN starts. We will determine the SP's scale, technical capabilities, region, industry reputation, etc., and we will understand their technical solutions (market, boost, hard disk) to develop related requirements.

For most SPs, they do not know about boost. In order to help them, we will first give SP a document, telling them where the boost version can be downloaded, how to deploy after downloading, etc. Since the boost port in the document is 16188, most customers may directly use port 16188 without modification.

The following is the boost document we provided to SP. I will send the full version of the document to RG on slack.

![WechatIMG996](https://github.com/filecoin-project/notary-governance/assets/129046880/b8362454-f0fa-438c-bb96-e6237bb198ce)

Just like the lotus node is configured with port 1234 by default, and the miner is configured with port 2345 by default, when there is a reference port, some people will always use the default port habitually in order to avoid trouble, and 16188 is a beloved number for Chinese people, we must not say that all sps that use 1234/2345 belong to the same company. it is definitely not possible!


Regarding the second allegations

We respect the rules of FIL+. Our LDN cooperates with at least 6 SPs. We are committed to achieving true decentralization. Each SP allocation of #1947 and #1948 does not exceed 25%. #2045 only uses the first three rounds. The DC usage is very small, and the maximum SP ratio is about 30%. We promise that the allocation of a single SP in #2045 will not exceed 20#% in the end.

#1947 We have cooperated with 11 SPs, and the maximum proportion of a single SP in 1947 does not exceed 23%
#1948 We have cooperated with 6 SPs, and the maximum proportion of a single SP in 1948 does not exceed 25%
#2045 We have cooperated with 9 SPs. At present, 2045 only used the first three rounds, and the DC usage is very small. The largest SP accounted for about 30%, and the next round can be improved immediately. The point, in order to show how much we attach great importance to this matter, since the launch of #917, we have re-screened the SP, and have stopped cooperating with the SP with the largest proportion in #2045.

We want to prove to the community that we are just a pure technical service provider without any interest chain. If RG and Filplus-govteam think that the SP we cooperate with is not suitable and there is a recommended SP, we are very happy to accept your suggestion.

As a senior Filecoin practitioner and builder, we always believe in Filecoin, RG and Filplus-govteam. We will send our boost deployment document version and the contracts signed by some of our customers with the computer room as "physical evidence" to RG before the meeting.

We hope that the misunderstanding about us can be clarified. If the community has any questions, we will discuss them at the trust or notary meeting tonight. Thank you for your support.

**Closed** 2023-07-28 14:30 UTC
Labels: Proposal
