### ISSUE TITLE
v5 Notary Allocator Application: LendMi 

### ISSUE THREAD

**Issue by SuperChaiChai** [filecoin-project/notary-governance#1014] opened 2023-12-21 07:04 UTC
# v5 Notary Allocator Application

To apply to be an allocator, organizations will submit one application for each proposed pathway to DataCap. If you will be designing multiple specific pathways, you will need to submit multiple applications. 

Please complete the following steps:
# 1. Fill out the information below and create a new GitHub Issue

1. Notary Allocator Pathway Name (This can be your name, or the name of your pathway/program. For example "E-Fil+"): LendMi Storage
2. Organization Name: LendMi
3. On-chain address for Allocator (Provide a NEW unique address. During ratification, you will need to initialize this address on-chain): f17gyewdt3aviprhmhcl52xq2rtv3ihrakiv6bukq
4. Country of Operation (Where your organization is legally based): Singapore
5. Region of Operation (What region will you serve?): North America / Asia Pacific
6. Type of Allocator, diligence process: (Automated/programmatic, Market-based, or Manual (human-in-the-loop at some phase): Manual
7. DataCap requested for allocator for 12 months of activity (This should be an estimate of overall expected activity. Estimate the total amount of DataCap you will be distributing to clients in 12 months, in TiB or PiB): 170 PiB

# 2. Access allocator application (download to save answers)
Click link below to access a Google doc version of the allocator application that can be used to save your answers if you are not prepared to fully submit the application in Step 3. https://docs.google.com/document/d/1-Ze8bo7ZlIJe8qX0YSFNPTka4CMprqoNB1D6V7WJJjo/copy

# 3. Submit allocation application 
Clink link below to access full allocator questionnaire and officially submit your answers:
https://airtable.com/appvyE0VHcgpAkt4Z/shrQxaAIsD693e1ns

Note: Sections of your responses WILL BE posted back into the GitHub issue tracking your application. 
The final section (Additional Disclosures) will NOT be posted to GitHub, and will be maintained by the Filecoin Foundation. 
Application information for notaries not accepted and ratified in this round will be deleted.

**Comment by Kevin-FF-USA** [comment] 2023-12-21 19:41
Hi @SuperChaiChai 
Wanted to let you know this application has been received. Also verifying you have submitted the Airtable form with your detailed Allocator plan - the public answers will be posted in a thread below soon. If you have any questions - please let me know.

**Comment by Filplus-govteam** [comment] 2023-12-30 22:46
Providing the information shared in Application for Public Review/Comment.

Basic Info

**1. Pathway Name:**
LendMi Storage

**2. Organization:**
LendMi

**3. Allocator's On-chain addresss:**
f17gyewdt3aviprhmhcl52xq2rtv3ihrakiv6bukq

**4. Country of Operation:**
Singapore

**5. Region(s) of operation:**
North America,Asia minus GCR

**6. Type of allocator: What is your overall diligence process? Automated (programmatic), Market-based, or Manual (human-in-the-loop at some phase). Initial allocations to these pathways will be capped.**
Manual

**7. Amount of DataCap Requested for allocator for 12 months:**
170 PiB

**8. Is your allocator providing a unique, new, or diverse pathway to DataCap? How does this allocator differentiate itself from other applicants, new or existing?**
We concentrated our efforts on engaging large corporations that hold significant data assets, while also catering to smaller data set owners from within the small and medium enterprise sector. Here are some examples of our clients:
Solana Lab - [filecoin-project/filecoin-plus-large-datasets#923](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/923) National Human Genome Research Institute - [filecoin-project/filecoin-plus-large-datasets#1642](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1642) Kernelogic - [filecoin-project/filecoin-plus-large-datasets#1637](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1637) ZINC15 - [filecoin-project/filecoin-plus-large-datasets#2244](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2244)

**9. As a member in the Filecoin Community, I acknowledge that I must adhere to the Community Code of Conduct, as well other End User License Agreements for accessing various tools and services, such as GitHub and Slack. Additionally, I will adhere to all local & regional laws & regulations that may relate to my role as a business partner, organization, notary, or other operating entity.  You can read the Filecoin Code of Conduct here: https://github.com/filecoin-project/community/blob/master/CODE_OF_CONDUCT.md**
Acknowledgment: Acknowledge

**Comment by Filplus-govteam** [comment] 2023-12-30 22:47
Client Diligence

**10. Who are your target clients?**
Small-scale developers or data owners,Enterprise Data Clients

**11. Describe in as much detail as possible how you will perform due diligence on clients.**
Our approach adopts a direct, manual strategy during the client evaluation phase, including conducting KYC processes as part of our comprehensive due diligence. Preliminary Client Inquiry Review: Our process initiates with an analysis of the client’s initial request. This involves gathering essential details about their business, specific needs for data storage, and overarching aims, which assists in initial screening and understanding the client’s profile. Detailed Needs Analysis: Our focus then shifts to a detailed examination of the client’s particular data storage needs, examining aspects such as data volume, type (including sensitivity or regulatory compliance aspects), and exact service requirements. This step is crucial in evaluating the data storage’s complexity and risk levels. Verification of Business and Background: We conduct an exhaustive check on the client’s business background. This includes authenticating their business registration, analyzing ownership details, and investigating any previous legal complications or issues. Financial health is also evaluated using financial statements and credit histories. Legal Compliance Assurance: It’s our priority to verify the client’s compliance with all pertinent legal and regulatory standards, especially those related to data handling and security, crucial for clients with sensitive or regulated data. Risk Analysis: We appraise potential risks involved in working with the client, including data security, legal, compliance, and reputational risks. This analysis helps in determining the required risk management approaches. Checking References: When relevant, we consult with the client’s former or current business partners or service providers for references, aiding in ascertaining the client's industry reputation and conduct. Engagement and Discussion: We conduct thorough discussions with the client’s principal contacts, either through virtual meetings or face-to-face, to assess the genuineness of their demands and to foster a rapport. Document and Contract Scrutiny: Before establishing any partnership, we rigorously review all relevant legal documents and contracts to ensure they align with our service quality and legal standards. Regular Monitoring and Review: Following client integration, we perform consistent reviews and surveillance to maintain ongoing adherence to compliance and to address any emerging issues in a timely manner.

**12. Please specify how many questions you'll ask, and provide a brief overview of the questions.**
Our current questionnaire is designed with 23 questions. These are intended for clients to furnish us with necessary details, ensuring we thoroughly cover all previously mentioned aspects. The questionnaire is available for your perusal at the following link . Please refer to the documents sent in private.

**13. Will you use a 3rd-party "Know your client" (KYC) service?**
We operate with an internal Compliance Department and a bespoke KYC Process. Once clients complete our comprehensive questionnaire, our compliance team embarks on the due diligence procedure. Tools like namescan.io could be employed in this process. This phase involves scrutinizing the type of data to be stored, ensuring alignment with laws pertinent to the business’s jurisdiction, and confirming the business’s licensure status. Additionally, we investigate the beneficiaries and principal stakeholders of the enterprise. Following the successful due diligence clearance, we initiate technical integrations and assist clients in the data transfer process.

**14. Can any client apply to your pathway, or will you be closed to only your own internal clients? (eg: bizdev or self-referral)**
Any client can apply.

**15. How do you plan to track the rate at which DataCap is being distributed to your clients?**
To monitor the distribution rate of DataCap to our clients, we intend to implement an automated system. This system will efficiently gather and record each client's DataCap usage data, which will then be displayed on a specialized dashboard for easy tracking and analysis.

**Comment by Filplus-govteam** [comment] 2023-12-30 22:49
Data Diligence

**16. As an operating entity in the Filecoin Community, you are required to follow all local & regional regulations relating to any data, digital and otherwise. This may include PII and data deletion requirements, as well as the storing, transmitting, or accessing of data.**
Acknowledgement: Acknowledge

**17. What type(s) of data would be applicable for your pathway?**
Public Open Dataset (Research/Non-Profit),Public Open Commercial/Enterprise,Private Commercial/Enterprise,Private Non-Profit/Social Impact

**18. How will you verify a client's data ownership? Will you use 3rd-party KYB (know your business) service to verify enterprise clients?**
Our verification procedure for establishing a client’s ownership of data is thorough and diversified, guaranteeing a rigorous validation process that respects confidentiality and adheres to data protection laws. The process involves several critical steps:
Initial Assessment of Data Ownership: Clients are required to submit evidence that substantiates their ownership or authorized rights over the data, including agreements of data acquisition, licensing documents, or legal declarations. For data originating within the client’s operations, we may request internal documents like organizational structures or data generation processes. Internal KYB Process for Corporate Clients: Our Compliance Department internally performs KYB verifications to confirm the legitimacy of the client’s business and their legal rights over the data. The process encompasses extensive checks on the business’s legal standing, ownership, regulatory adherence, and reputational aspects. Risk assessment during KYB includes reviewing global sanctions lists, PEP lists, and adverse media reports. Investigation of Data Origins and Lifecycle: We conduct thorough investigations into the data’s origins, movements, and overall lifecycle, reviewing the client's data management history and relevant transfer documents. For data that is sensitive or under regulation, we demand additional compliance evidence, in line with laws such as GDPR or HIPAA. Direct Client Engagement and Clarification: We conduct personal interviews or meetings with clients to delve deeper into their data management methods and clarify any ambiguities in the documentation. Consistent Audits and Monitoring: Ongoing audits and regular checks are performed after client integration to ensure they continue to comply with data ownership and authenticity standards.
This detailed verification framework ensures that we have a solid and trustworthy method to verify data ownership, keeping pace with evolving legal requirements and KYB technological advancements.

**19. How will you ensure the data meets local & regional legal requirements?**
To ensure client data adheres to regional and local legal standards, our process includes completing a KYC form as part of our onsite KYB process, all managed by our Compliance Department. Comprehensive Legal Compliance Framework: Ongoing monitoring and research into local and regional data storage, privacy, and security laws are a core part of our strategy, including regulations such as the GDPR, CCPA and PDPA. Collaboration with legal experts ensures we effectively apply these laws in our operations. We devise region-specific compliance strategies, tailoring our data storage services to meet diverse legal requirements. Our clients operating globally receive advice on multi-jurisdictional compliance to ensure legal adherence in all operational regions. Client Support and Guidance: Our client education program includes workshops and training focused on legal compliance, supported by extensive guides. For intricate legal matters, we offer bespoke consultation services. Contractual Agreements and Regular Audits: Our data processing and transfer agreements are comprehensive, aligning with the legal requirements of various regions. We maintain legal compliance through regular audits, promptly rectifying any non-compliance issues. Legal and Data Protection Oversight: Our Data Protection Officer and legal team oversee all aspects of data-related legal compliance. They also provide guidance on legal matters to our clients, ensuring our practices are consistent with the latest legal standards. This strategy ensures our clients' data management practices fully comply with all necessary legal requirements, effectively mitigating legal risks for both our clients and our organization. Here is our reference sheet for geographical data regulation. Please refer to the privately sent message:

**20. What types of data preparation will you support or require?**
Our services include complete technical assistance for our clients, which covers both integration and data preparation. For those with Big Data requirements, we extend services that allow for the physical transfer of their data to our storage devices. For smaller entities and individual users, we make available an API to streamline the data transfer process.

**21. What tools or methodology will you use to sample and verify the data aligns with your pathway?**
For verification purposes, we will implement a method where we randomly select one record for inspection. This approach helps ensure the data's authenticity and adherence to specified requirements. Additionally, we will adopt a progressive release strategy for DataCap, contingent upon successful verification of the data and its utilization of space. This method is also intended to prevent misuse, such as sector padding.

**Comment by Filplus-govteam** [comment] 2023-12-30 22:51
Data Distribution

**22. How many replicas will you require to meet programmatic requirements for distribution?**
5+

**23. What geographic or regional distribution will you require?**
North America and Asia

**24. How many Storage Provider owner/operators will you require to meet programmatic requirements for distribution?**
5+

**25. Do you require equal percentage distribution for your clients to their chosen SPs? Will you require preliminary SP distribution plans from the client before allocating any DataCap?**
This question is answered in an open-ended question in our CDD form. Please refer to the document sent in private.

**26. What tooling will you use to verify client deal-making distribution?**
We use datacapstats.io

**27. How will clients meet SP distribution requirements?**
Our approach includes offering an easy-to-use API/SDK, which clients can utilize to efficiently transfer their data to the designated storage provider.

**28. As an allocator, do you support clients that engage in deal-making with SPs utilizing a VPN?**
To verify whether storage providers are using VPNs, we utilize third-party services. One such resource is the VPN/IP Address Check by IPQualityScore, available at https://www.ipqualityscore.com/vpn-ip-address-check. For comprehensive checks, we also leverage MaxMind's services (https://www.maxmind.com/).

**Comment by Filplus-govteam** [comment] 2023-12-30 22:52
Datacap Allocation Atrategy

**29. Will you use standardized DataCap allocations to clients?**
No, client specific

**30. Allocation Tranche Schedule to clients:**
• First: 1 PiB • Second: 2 PiB • Third: 3 PiB • Fourth: 4 PiB • Max per client overall: 10 PiB

**31. Will you use programmatic or software based allocations?**
No, manually calculated & determined

**32. What tooling will you use to construct messages and send allocations to clients?**
Currently, our approach involves directly communicating with clients, through Slack. We plan to manually craft messages and then proceed to send DataCap allocations to our clients through these personalized communications.

**33. Describe the process for granting additional DataCap to previously verified clients.**
There are no concrete plans for now.

**Comment by Filplus-govteam** [comment] 2023-12-30 22:53
Tools and Bookkeeping

**34. Describe in as much detail as possible the tools used for: • client discoverability & applications • due diligence & investigation • bookkeeping • on-chain message construction • client deal-making behavior • tracking overall allocator health • dispute discussion & resolution • community updates & comms**
Client Discoverability & Applications: Primary platforms include our Website and GitHub, with Discord serving as the main channel for the application process. Due Diligence & Investigation: We use IPQualityScore (https://www.ipqualityscore.com/vpn-ip-address-check) for VPN checks. For comprehensive checks, we also leverage MaxMind's services (https://www.maxmind.com/) and Namescan.io for compliance checks. Bookkeeping: A programmed Excel file specifically designed for our bookkeeping needs. On-Chain Message Construction: Our process employs a custom-developed Software Development Kit (SDK). Client Deal-Making Behavior Analysis: We utilize Filecoin Boost alongside other analytic tools like Chainalysis for deeper insights. Tracking Allocator Health: A bespoke Dashboard is used for tracking and monitoring allocation activities. Dispute Discussion & Resolution: Discord and GitHub are our primary platforms for handling disputes. Community Updates & Communications: Updates and communications are conducted through Discord and GitHub, supplemented by periodic newsletters via Mailchimp for broader outreach. Likely based on our past experience, it could be held provided once a quarter.

**35. Will you use open-source tooling from the Fil+ team?**
We use FIL+ team's Github.

**36. Where will you keep your records for bookkeeping? How will you maintain transparency in your allocation decisions?**
Our record maintenance involves using GitHub for public storage of certain client details and private emails and our own secure data storage for confidential information. The bookkeeping is handled through a specially programmed Excel sheet, closely monitored by our operations staff. For transparency, we will publicly share certain information on GitHub, providing community access for auditability. More sensitive data will be kept private but will be available to the Fil+ Governance team as needed for resolving disputes or conducting audits. Requests for further information can be made through our official email contact points.

**Comment by Filplus-govteam** [comment] 2023-12-30 22:55
Risk Mitigation, Auditing, Compliance

**37. Describe your proposed compliance check mechanisms for your own clients.
Our dispute handling process is structured to swiftly and transparently address any disagreements within the context of DataCap allocation on the Filecoin network, be it internal or external.**
Initial Steps and Timely Response: Upon receiving a dispute notice, we promptly initiate an assessment within 120 hours to understand the dispute's nature, covering aspects like DataCap distribution, data compliance, or storage deal executions. All involved parties are immediately notified of the dispute and are provided with an estimated timeline for its resolution.
In-depth Information Analysis: We gather and scrutinize all relevant data, including communication logs, DataCap allocation records, and storage deal agreements, to pinpoint the dispute's root cause and the legitimacy of claims.
Conducting Resolution Discussions: Meetings are arranged with concerned parties. Internal disputes involve discussions with our clients to seek a mutually agreeable solution, while external disputes entail preparing a robust defense of our decisions for review by other notaries or the Fil+ Governance Team.
Mediation and Resolution Process: When necessary, we resort to mediation, involving neutral third-party mediators to facilitate agreeable solutions. Our aim is to amicably settle disputes while strictly adhering to the Filecoin network's standards and fairness principles.
Maintaining Transparency and Record-Keeping: Transparency is paramount in our process; all decisions and outcomes are meticulously documented and shared, including public disclosure on GitHub where appropriate. We maintain comprehensive records of all disputes for internal auditing and compliance.
Accountability and Continuous Improvement: Should our fault be identified in a dispute, we accept full responsibility and promptly enact corrective measures. Post-dispute, we review and refine our policies to prevent recurrence and enhance our processes. Engagement with Community and Governance Bodies:
In broader community or governance-related disputes, we actively involve the community for feedback and explanation of our stance. We adhere to the Fil+ Governance Team's decisions and follow any directives arising from dispute resolutions. Our dispute resolution framework is designed to efficiently and equitably resolve issues, ensuring every party's voice is heard and resolutions align with Filecoin's overarching objectives.

**38. Describe your process for handling disputes. Highlight response times, transparency, and accountability mechanisms.**
Our dispute handling process is structured to swiftly and transparently address any disagreements within the context of DataCap allocation on the Filecoin network, be it internal or external.
Initial Steps and Timely Response: Upon receiving a dispute notice, we promptly initiate an assessment within 120 hours to understand the dispute's nature, covering aspects like DataCap distribution, data compliance, or storage deal executions. All involved parties are immediately notified of the dispute and are provided with an estimated timeline for its resolution. In-depth Information Analysis: We gather and scrutinize all relevant data, including communication logs, DataCap allocation records, and storage deal agreements, to pinpoint the dispute's root cause and the legitimacy of claims. Conducting Resolution Discussions: Meetings are arranged with concerned parties. Internal disputes involve discussions with our clients to seek a mutually agreeable solution, while external disputes entail preparing a robust defense of our decisions for review by other notaries or the Fil+ Governance Team. Mediation and Resolution Process: When necessary, we resort to mediation, involving neutral third-party mediators to facilitate agreeable solutions. Our aim is to amicably settle disputes while strictly adhering to the Filecoin network's standards and fairness principles. Maintaining Transparency and Record-Keeping: Transparency is paramount in our process; all decisions and outcomes are meticulously documented and shared, including public disclosure on GitHub where appropriate. We maintain comprehensive records of all disputes for internal auditing and compliance. Accountability and Continuous Improvement: Should our fault be identified in a dispute, we accept full responsibility and promptly enact corrective measures. Post-dispute, we review and refine our policies to prevent recurrence and enhance our processes. Engagement with Community and Governance Bodies: In broader community or governance-related disputes, we actively involve the community for feedback and explanation of our stance. We adhere to the Fil+ Governance Team's decisions and follow any directives arising from dispute resolutions. Our dispute resolution framework is designed to efficiently and equitably resolve issues, ensuring every party's voice is heard and resolutions align with Filecoin's overarching objectives.

**39. Detail how you will announce updates to tooling, pathway guidelines, parameters, and process alterations.**
Currently, we have not formalized a specific plan for announcing updates to our tooling, guidelines, or processes. However, when these updates are ready, we anticipate communicating them through our Discord channel and on our official website. This approach will ensure our clients and stakeholders are kept informed about any significant changes in a timely and efficient manner.

**40. How long will you allow the community to provide feedback before implementing changes?**
Our approach includes maintaining open channels for online communication with the community, primarily via GitHub and Discord. This will allow us to actively engage with our community members and allocate a suitable timeframe for them to offer feedback on proposed changes. We will moderate and facilitate discussions on these platforms to ensure productive engagement, and the feedback gathered will be thoughtfully evaluated to inform our implementation strategy.

**41. Regarding security, how will you structure and secure the on-chain notary address? If you will utilize a multisig, how will it be structured? Who will have administrative & signatory rights?**
We are in the process of establishing a secure structure for our on-chain notary address, which will incorporate the use of Safe Wallet for Multi-Signature capabilities. This approach is under active development and will undergo extensive testing to validate its effectiveness before it goes live. Concurrently, we are considering business strategies that enable us to handle all client transactions directly and perform settlements off-chain, adding an extra layer of security and operational control.

**42. Will you deploy smart contracts for program or policy procedures? If so, how will you track and fund them?**
We intend to implement smart contracts as part of our program and policy procedures. The likely approach will involve a pooled funding mechanism from our clients' end. Additionally, we plan to integrate these smart contracts with a multi-signature system in collaboration with the allocated Storage Providers (SPs). This integration will ensure enhanced security and efficient contract execution.

**Comment by Filplus-govteam** [comment] 2023-12-30 22:56
Monetization

**43. Outline your monetization models for the services you provide as a notary allocator pathway.**
We operate on a commission model for our market matching services as a notary allocator. Alongside this, we plan to establish lending and borrowing avenues as additional revenue streams. Specific pricing details for our range of services, including application processing, data preparation, data clearinghouse distribution, and audit services, are set to align with market standards while offering value to our clients.

**44. Describe your organization's structure, such as the legal entity and other business & market ventures.**
Eventually, we aim to transition into a prominent lending and borrowing platform where storage space can be rented and filecoins can be lent and borrowed freely in an automated manner. But currently we will work with the manual approach. This format provides a solid foundation for our business and market activities, as we gradually progress towards achieving our aspirations.

**45. Where will accounting for fees be maintained?**
Our fee accounting, encompassing aspects like staking, burning, and releasing funds, is conducted entirely on-chain. This method guarantees full transparency and facilitates auditing by the Fil+ Governance body and other relevant stakeholders, aligning with our commitment to transparent and responsible financial operations.

**Comment by Filplus-govteam** [comment] 2023-12-30 22:56
Pat Experience, Affiliations, Reputation

**46. If you've received DataCap allocation privileges before, please link to prior notary applications.**
[filecoin-project/notary-governance#455](https://github.com/filecoin-project/notary-governance/issues/455)

**47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.**
We are a financial company offering blockchain services to our clients.

**48. How are you estimating your client demand and pathway usage? Do you have existing clients and an onboarding funnel?**
We have existing clients

**Comment by SuperChaiChai** [comment] 2024-01-19 06:05
Hi @Kevin-FF-USA  , We'd like to improve the answer to the following question:

47. How are you connected to the Filecoin ecosystem? Describe your (or your organization's) Filecoin relationships, investments, or ownership.

We are a financial company offering blockchain services to our clients. We have also worked with multiple partners to promote filecoin tools and ecosystem. such as:
https://x.com/LendMi_Official/status/1463093671859945476?s=20

**Comment by galen-mcandrew** [comment] 2024-03-14 07:04
## Datacap Request for Allocator
#### Address
> f2ru35g5sjz7q5atm6mb6nh7bo7tastgluqydxsoa
#### Datacap Allocated
> 5PiB

**Comment by galen-mcandrew** [comment] 2024-11-02 20:52
## Datacap Request for Allocator
#### Address
> f2ru35g5sjz7q5atm6mb6nh7bo7tastgluqydxsoa
#### Datacap Allocated
> 2.5PiB

**Comment by galen-mcandrew** [comment] 2024-11-21 19:37
bafy2bzaceaisy5mgnvnkwoh5krhnw772yk57eq5ru4tnbptvsw32qxpxb5tpy

**Closed by galen-mcandrew** 2024-11-21 19:37 UTC
Labels: Notary Application, ready to sign, Round 5 - Allocator, start sign datacap
